(** * CakeML [reg_alloc]: the monadic graph-colouring register allocator

    A port of [compiler/backend/reg_alloc/reg_allocScript.sml] (definitions
    only; the theorem [convention_partitions] is not ported yet).

    The allocator runs in the state-exception monad of [ml_monadBase]
    ([M ra_state A state_exn], abbreviated [RA A]).  HOL generates a number of
    functions with ML code rather than [Definition]s; they are written out
    here by hand with HOL's names and HOL's exact definitions, and are not
    tagged (there is no HOL declaration to cite):
    - [define_monad_access_funs ``:ra_state``]: [get_f]/[set_f] for every
      field [f] ([get_f = \state. (M_success state.f, state)],
      [set_f x = \state. (M_success (), state with f := x)]);
    - [define_monad_exception_functions ``:state_exn`` ``:ra_state``]:
      [raise_Fail], [raise_Subscript], [handle_Fail], [handle_Subscript];
    - [define_MFarray_manip_funs] for the fixed-size arrays [adj_ls],
      [node_tag], [degrees], [coalesced], [move_related]: [f_length]
      ([Marray_length]), [f_sub] ([Marray_sub] raising [Subscript]) and
      [update_f] ([Marray_update] raising [Subscript]);
    - [define_run ``:ra_state`` [...] "ira_state"]: the record [ira_state]
      (array fields replaced by [(size, initial value)] pairs; its field
      names are prefixed with [ira_state_] because Rocq record fields share
      the module namespace with [ra_state]'s) and [run_ira_state].

    The arrays are HOL lists, accessed and updated in linear time
    ([Msub]/[Mupdate]); this is HOL's semantics (out-of-bounds accesses raise
    [Subscript]).

    Naming: HOL's [clash_tree] constructor [Set] is [Set_] ([Set] is a Rocq
    keyword).  [coalesce_parent] and [coalesce_root] recurse on a smaller
    node index ([xt < x]); they are defined with [Fix] on [<] over [N] and
    HOL's equations are the tagged [_def] theorems.  [rpt_do_step] recurses
    on [SUC c] and uses [num_rec].  [lookup_any] ([miscScript]) is not in
    [misc.v] yet and is defined locally (untagged). *)

From Galette Require Import Base.
From Galette.HOL.src.num.theories Require Import arithmetic.
From Galette.HOL.src.list.src Require Import list rich_list numposrep.
From Galette.HOL.src.coretypes Require Import pair.
From Galette.HOL.src.string Require Import string.
From Galette.HOL.src.finite_maps Require Import sptree.
From Galette.HOL.src.sort Require Import sorting.
From Galette.cakeml.basis.pure Require Import mllist.
From Galette.cakeml.translator.monadic.monad_base Require Import ml_monadBase.
Open Scope N_scope.
Open Scope monad_scope.

(** [miscScript]'s [lookup_any] (not yet in [misc.v]; untagged copy). *)
Definition lookup_any {A} (x : N) (sp : num_map A) (d : A) : A :=
  match lookup x sp with None => d | Some m => m end.

(** ** Tags and the allocator state *)

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "tag" *)
Inductive tag : Type :=
| Fixed : N -> tag
| Atemp : tag
| Stemp : tag.

#[global] Instance tag_eq_dec : EqDecision tag.
Proof.
  intros [m| |] [n| |]; try (right; discriminate); try (left; reflexivity).
  destruct (decide (m = n)) as [->|ne]; [left; reflexivity|right; congruence].
Defined.

#[global] Instance tag_inhabited : Inhabited tag := Atemp.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "ra_state" *)
Record ra_state : Type := mk_ra_state {
  adj_ls : marray (list N);
  node_tag : marray tag;
  degrees : marray N;
  dim : N;
  simp_wl : list N;
  spill_wl : list N;
  freeze_wl : list N;
  avail_moves_wl : list (N * (N * N));
  unavail_moves_wl : list (N * (N * N));
  coalesced : marray N;
  move_related : marray bool;
  stack : list N
}.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "state_exn" *)
Inductive state_exn : Type :=
| Fail : string -> state_exn
| Subscript : state_exn.

(** The allocator monad. *)
Abbreviation RA A := (M ra_state A state_exn).

(** ** Generated accessors, exception functions and array functions *)

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_adj_ls {E} : M ra_state (list (list N)) E := fun state => (M_success state.(adj_ls), state).
Definition set_adj_ls {E} (x : list (list N)) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state x state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_node_tag {E} : M ra_state (list tag) E := fun state => (M_success state.(node_tag), state).
Definition set_node_tag {E} (x : list tag) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) x state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_degrees {E} : M ra_state (list N) E := fun state => (M_success state.(degrees), state).
Definition set_degrees {E} (x : list N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) x state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_dim {E} : M ra_state (N) E := fun state => (M_success state.(dim), state).
Definition set_dim {E} (x : N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) x state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_simp_wl {E} : M ra_state (list N) E := fun state => (M_success state.(simp_wl), state).
Definition set_simp_wl {E} (x : list N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) x state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_spill_wl {E} : M ra_state (list N) E := fun state => (M_success state.(spill_wl), state).
Definition set_spill_wl {E} (x : list N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) x state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_freeze_wl {E} : M ra_state (list N) E := fun state => (M_success state.(freeze_wl), state).
Definition set_freeze_wl {E} (x : list N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) x state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_avail_moves_wl {E} : M ra_state (list (N * (N * N))) E := fun state => (M_success state.(avail_moves_wl), state).
Definition set_avail_moves_wl {E} (x : list (N * (N * N))) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) x state.(unavail_moves_wl) state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_unavail_moves_wl {E} : M ra_state (list (N * (N * N))) E := fun state => (M_success state.(unavail_moves_wl), state).
Definition set_unavail_moves_wl {E} (x : list (N * (N * N))) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) x state.(coalesced) state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_coalesced {E} : M ra_state (list N) E := fun state => (M_success state.(coalesced), state).
Definition set_coalesced {E} (x : list N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) x state.(move_related) state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_move_related {E} : M ra_state (list bool) E := fun state => (M_success state.(move_related), state).
Definition set_move_related {E} (x : list bool) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) x state.(stack)).

(** Generated by HOL's [define_monad_access_funs] (no HOL source declaration). *)
Definition get_stack {E} : M ra_state (list N) E := fun state => (M_success state.(stack), state).
Definition set_stack {E} (x : list N) : M ra_state unit E :=
  fun state => (M_success tt, mk_ra_state state.(adj_ls) state.(node_tag) state.(degrees) state.(dim) state.(simp_wl) state.(spill_wl) state.(freeze_wl) state.(avail_moves_wl) state.(unavail_moves_wl) state.(coalesced) state.(move_related) x).

(** Generated by HOL's [define_MFarray_manip_funs]. *)
Definition adj_ls_length {E} : M ra_state N E := Marray_length (fun s => s.(adj_ls)).
Definition adj_ls_sub : N -> M ra_state (list N) state_exn := Marray_sub (fun s => s.(adj_ls)) Subscript.
Definition update_adj_ls : N -> (list N) -> M ra_state unit state_exn :=
  Marray_update (fun s => s.(adj_ls)) (fun x s => mk_ra_state x s.(node_tag) s.(degrees) s.(dim) s.(simp_wl) s.(spill_wl) s.(freeze_wl) s.(avail_moves_wl) s.(unavail_moves_wl) s.(coalesced) s.(move_related) s.(stack)) Subscript.

(** Generated by HOL's [define_MFarray_manip_funs]. *)
Definition node_tag_length {E} : M ra_state N E := Marray_length (fun s => s.(node_tag)).
Definition node_tag_sub : N -> M ra_state tag state_exn := Marray_sub (fun s => s.(node_tag)) Subscript.
Definition update_node_tag : N -> tag -> M ra_state unit state_exn :=
  Marray_update (fun s => s.(node_tag)) (fun x s => mk_ra_state s.(adj_ls) x s.(degrees) s.(dim) s.(simp_wl) s.(spill_wl) s.(freeze_wl) s.(avail_moves_wl) s.(unavail_moves_wl) s.(coalesced) s.(move_related) s.(stack)) Subscript.

(** Generated by HOL's [define_MFarray_manip_funs]. *)
Definition degrees_length {E} : M ra_state N E := Marray_length (fun s => s.(degrees)).
Definition degrees_sub : N -> M ra_state N state_exn := Marray_sub (fun s => s.(degrees)) Subscript.
Definition update_degrees : N -> N -> M ra_state unit state_exn :=
  Marray_update (fun s => s.(degrees)) (fun x s => mk_ra_state s.(adj_ls) s.(node_tag) x s.(dim) s.(simp_wl) s.(spill_wl) s.(freeze_wl) s.(avail_moves_wl) s.(unavail_moves_wl) s.(coalesced) s.(move_related) s.(stack)) Subscript.

(** Generated by HOL's [define_MFarray_manip_funs]. *)
Definition coalesced_length {E} : M ra_state N E := Marray_length (fun s => s.(coalesced)).
Definition coalesced_sub : N -> M ra_state N state_exn := Marray_sub (fun s => s.(coalesced)) Subscript.
Definition update_coalesced : N -> N -> M ra_state unit state_exn :=
  Marray_update (fun s => s.(coalesced)) (fun x s => mk_ra_state s.(adj_ls) s.(node_tag) s.(degrees) s.(dim) s.(simp_wl) s.(spill_wl) s.(freeze_wl) s.(avail_moves_wl) s.(unavail_moves_wl) x s.(move_related) s.(stack)) Subscript.

(** Generated by HOL's [define_MFarray_manip_funs]. *)
Definition move_related_length {E} : M ra_state N E := Marray_length (fun s => s.(move_related)).
Definition move_related_sub : N -> M ra_state bool state_exn := Marray_sub (fun s => s.(move_related)) Subscript.
Definition update_move_related : N -> bool -> M ra_state unit state_exn :=
  Marray_update (fun s => s.(move_related)) (fun x s => mk_ra_state s.(adj_ls) s.(node_tag) s.(degrees) s.(dim) s.(simp_wl) s.(spill_wl) s.(freeze_wl) s.(avail_moves_wl) s.(unavail_moves_wl) s.(coalesced) x s.(stack)) Subscript.


(** Generated by HOL's [define_monad_exception_functions]. *)
Definition raise_Fail {A} (e1 : string) : RA A := fun state => (M_failure (Fail e1), state).
Definition raise_Subscript {A} : RA A := fun state => (M_failure Subscript, state).

Definition handle_Fail {A} (x : RA A) (f : string -> RA A) : RA A :=
  fun state =>
    let '(res, state) := x state in
    match res with
    | M_success y => (M_success y, state)
    | M_failure e =>
        match e with
        | Fail e1 => f e1 state
        | Subscript => (M_failure Subscript, state)
        end
    end.

Definition handle_Subscript {A} (x : RA A) (f : RA A) : RA A :=
  fun state =>
    let '(res, state) := x state in
    match res with
    | M_success y => (M_success y, state)
    | M_failure e =>
        match e with
        | Fail e1 => (M_failure (Fail e1), state)
        | Subscript => f state
        end
    end.

(** ** Monadic list functions *)

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_FOREACH_def" *)
Fixpoint st_ex_FOREACH {S A B E} (l : list A) (a : A -> M S B E) : M S unit E :=
  match l with
  | [] => st_ex_return tt
  | x :: xs => a x ;; st_ex_FOREACH xs a
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_MAP_def" *)
Fixpoint st_ex_MAP {S A B E} (f : A -> M S B E) (l : list A) : M S (list B) E :=
  match l with
  | [] => st_ex_return []
  | x :: xs =>
      fx <- f x ;;
      fxs <- st_ex_MAP f xs ;;
      st_ex_return (fx :: fxs)
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_PARTITION_def" *)
Fixpoint st_ex_PARTITION {S A E} (P : A -> M S bool E) (l : list A) (tt_ ff : list A)
    : M S (list A * list A) E :=
  match l with
  | [] => st_ex_return (tt_, ff)
  | x :: xs =>
      Px <- P x ;;
      if Px then st_ex_PARTITION P xs (x :: tt_) ff
      else st_ex_PARTITION P xs tt_ (x :: ff)
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_FILTER_def" *)
Fixpoint st_ex_FILTER {S A E} (P : A -> M S bool E) (l : list A) (acc : list A)
    : M S (list A) E :=
  match l with
  | [] => st_ex_return acc
  | x :: xs =>
      Px <- P x ;;
      if Px then st_ex_FILTER P xs (x :: acc)
      else st_ex_FILTER P xs acc
  end.

(** ** Adjacency lists (sorted by [>]) *)

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "sorted_insert_def" *)
Fixpoint sorted_insert (x : N) (acc : list N) (l : list N) : list N :=
  match l with
  | [] => REVERSE (x :: acc)
  | y :: ys =>
      if x =? y then REVERSE acc ++ y :: ys
      else if y <? x then REVERSE acc ++ x :: y :: ys
      else sorted_insert x (y :: acc) ys
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "sorted_mem_def" *)
Fixpoint sorted_mem (x : N) (l : list N) : bool :=
  match l with
  | [] => false
  | y :: ys =>
      if x =? y then true
      else if y <? x then false
      else sorted_mem x ys
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "insert_edge_def" *)
Definition insert_edge (x y : N) : RA unit :=
  adjx <- adj_ls_sub x ;;
  adjy <- adj_ls_sub y ;;
  update_adj_ls x (sorted_insert y [] adjx) ;;
  update_adj_ls y (sorted_insert x [] adjy).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "list_insert_edge_def" *)
Fixpoint list_insert_edge (x : N) (l : list N) : RA unit :=
  match l with
  | [] => st_ex_return tt
  | y :: ys => insert_edge x y ;; list_insert_edge x ys
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "clique_insert_edge_def" *)
Fixpoint clique_insert_edge (l : list N) : RA unit :=
  match l with
  | [] => st_ex_return tt
  | x :: xs => list_insert_edge x xs ;; clique_insert_edge xs
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "extend_clique_def" *)
Fixpoint extend_clique (l : list N) (cli : list N) : RA (list N) :=
  match l with
  | [] => st_ex_return cli
  | x :: xs =>
      if MEM x cli then extend_clique xs cli
      else list_insert_edge x cli ;; extend_clique xs (x :: cli)
  end.

(** ** The allocator heuristics *)

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "dec_deg_def" *)
Definition dec_deg (n : N) : RA unit :=
  cd <- degrees_sub n ;;
  update_degrees n (cd - 1).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "dec_degree_def" *)
Definition dec_degree (n : N) : RA unit :=
  d <- get_dim ;;
  if n <? d then
    adjs <- adj_ls_sub n ;;
    st_ex_FOREACH adjs dec_deg
  else st_ex_return tt.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "add_simp_wl_def" *)
Definition add_simp_wl (ls : list N) : RA unit :=
  swl <- get_simp_wl ;;
  set_simp_wl (ls ++ swl).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "add_spill_wl_def" *)
Definition add_spill_wl (ls : list N) : RA unit :=
  swl <- get_spill_wl ;;
  set_spill_wl (ls ++ swl).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "add_freeze_wl_def" *)
Definition add_freeze_wl (ls : list N) : RA unit :=
  fwl <- get_freeze_wl ;;
  set_freeze_wl (ls ++ fwl).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "push_stack_def" *)
Definition push_stack (x : N) : RA unit :=
  swl <- get_stack ;;
  update_degrees x 0 ;;
  update_move_related x false ;;
  set_stack (x :: swl).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "add_unavail_moves_wl_def" *)
Definition add_unavail_moves_wl (ls : list (N * (N * N))) : RA unit :=
  swl <- get_unavail_moves_wl ;;
  set_unavail_moves_wl (ls ++ swl).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_not_coalesced_def" *)
Definition is_not_coalesced (d : N) : RA bool :=
  dt <- coalesced_sub d ;;
  st_ex_return (d =? dt).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "split_degree_def" *)
Definition split_degree (d k v : N) : RA bool :=
  if v <? d then
    vd <- degrees_sub v ;;
    b <- is_not_coalesced v ;;
    st_ex_return ((vd <? k) && b)
  else st_ex_return true.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "sort_moves_def" *)
Definition sort_moves {A} (ls : list (N * A)) : list (N * A) :=
  sort (fun '(p, x) '(p', x') => p' <? p) ls.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "smerge_def" *)
Fixpoint smerge {A} (xs ys : list (N * A)) : list (N * A) :=
  match xs with
  | [] => ys
  | (p, m) :: xs' =>
      (fix smerge_r (ys : list (N * A)) : list (N * A) :=
         match ys with
         | [] => (p, m) :: xs'
         | (p', m') :: ys' =>
             if p' <=? p then (p, m) :: smerge xs' ((p', m') :: ys')
             else (p', m') :: smerge_r ys'
         end) ys
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "revive_moves_def" *)
Definition revive_moves (vs : list N) : RA unit :=
  nbs <- st_ex_MAP adj_ls_sub vs ;;
  uam <- get_unavail_moves_wl ;;
  am <- get_avail_moves_wl ;;
  let '(rev, unavail) :=
    PARTITION (fun '(_, (x, y)) => EXISTS (sorted_mem x) nbs || EXISTS (sorted_mem y) nbs) uam in
  let sorted := smerge (sort_moves rev) am in
  set_avail_moves_wl sorted ;;
  set_unavail_moves_wl unavail.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "unspill_def" *)
Definition unspill (k : N) : RA unit :=
  d <- get_dim ;;
  swl <- get_spill_wl ;;
  '(ltk, gtk) <- st_ex_PARTITION (split_degree d k) swl [] [] ;;
  revive_moves ltk ;;
  '(ltkfreeze, ltksimp) <- st_ex_PARTITION move_related_sub ltk [] [] ;;
  set_spill_wl gtk ;;
  add_simp_wl ltksimp ;;
  add_freeze_wl ltkfreeze.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_simplify_def" *)
Definition do_simplify (k : N) : RA bool :=
  simps <- get_simp_wl ;;
  if NULL simps then st_ex_return false
  else
    st_ex_FOREACH simps dec_degree ;;
    st_ex_FOREACH simps push_stack ;;
    set_simp_wl [] ;;
    unspill k ;;
    st_ex_return true.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "inc_deg_def" *)
Definition inc_deg (n d : N) : RA unit :=
  cd <- degrees_sub n ;;
  update_degrees n (cd + d).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_Fixed_def" *)
Definition is_Fixed (x : N) : RA bool :=
  xt <- node_tag_sub x ;;
  st_ex_return (match xt with Fixed n => true | _ => false end).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_coalesce_real_def" *)
Definition do_coalesce_real (x y : N) (case1 case2 : list N) : RA unit :=
  update_coalesced y x ;;
  bx <- is_Fixed x ;;
  (if bx then st_ex_return tt else inc_deg x (LENGTH case2)) ;;
  list_insert_edge x case2 ;;
  st_ex_FOREACH case1 dec_deg ;;
  push_stack y.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_Atemp_def" *)
Definition is_Atemp (d : N) : RA bool :=
  dt <- node_tag_sub d ;;
  st_ex_return (bool_decide (dt = Atemp)).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_Fixed_k_def" *)
Definition is_Fixed_k (k x : N) : RA bool :=
  xt <- node_tag_sub x ;;
  st_ex_return (match xt with Fixed n => n <? k | _ => false end).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "considered_var_def" *)
Definition considered_var (k x : N) : RA bool :=
  bx <- is_Atemp x ;;
  fx <- is_Fixed_k k x ;;
  st_ex_return (bx || fx).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "deg_or_inf_def" *)
Definition deg_or_inf (k x : N) : RA N :=
  bx <- is_Fixed_k k x ;;
  if bx then st_ex_return k else degrees_sub x.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "bg_ok_def" *)
Definition bg_ok (k x y : N) : RA (option (list N * list N)) :=
  adjx <- adj_ls_sub x ;;
  adjy <- adj_ls_sub y ;;
  let '(case1, case2) := PARTITION (fun v => sorted_mem v adjx) adjy in
  case1 <- st_ex_FILTER (considered_var k) case1 [] ;;
  case2 <- st_ex_FILTER (considered_var k) case2 [] ;;
  case2degs <- st_ex_MAP (deg_or_inf k) case2 ;;
  let c2len := LENGTH (FILTER (fun x => k <=? x) case2degs) in
  if c2len =? 0 then st_ex_return (Some (case1, case2))
  else
    let case3 := FILTER (fun v => negb (sorted_mem v adjy)) adjx in
    case3 <- st_ex_FILTER (considered_var k) case3 [] ;;
    case1degs <- st_ex_MAP (deg_or_inf (k + 1)) case1 ;;
    case3degs <- st_ex_MAP (deg_or_inf k) case3 ;;
    c1len <- st_ex_return (LENGTH (FILTER (fun x => k <=? x - 1) case1degs)) ;;
    c3len <- st_ex_return (LENGTH (FILTER (fun x => k <=? x) case3degs)) ;;
    if c1len + c2len + c3len <? k then st_ex_return (Some (case1, case2))
    else st_ex_return None.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "consistency_ok_def" *)
Definition consistency_ok (x y : N) : RA bool :=
  if x =? y then st_ex_return false
  else
    adjy <- adj_ls_sub y ;;
    if sorted_mem x adjy then st_ex_return false
    else
      bx <- is_Fixed x ;;
      by_ <- is_Fixed y ;;
      movrelx <- move_related_sub x ;;
      movrely <- move_related_sub y ;;
      st_ex_return ((bx || movrelx) && (by_ || movrely) && negb (bx && by_)).

Lemma coalesce_dec (x xt : N) : (x <=? xt) = false -> xt < x.
Proof. intros H; apply N.leb_gt, H. Qed.

Definition coalesce_parent_F (x : N) (rec : forall y, y < x -> RA N) : RA N :=
  xt <- coalesced_sub x ;;
  bx <- is_Fixed xt ;;
  if bx then st_ex_return xt
  else
    match Sumbool.sumbool_of_bool (x <=? xt) with
    | left _ => st_ex_return x
    | right H =>
        anc <- rec xt (coalesce_dec x xt H) ;;
        update_coalesced x anc ;;
        st_ex_return anc
    end.

(** HOL [coalesce_parent] (see [coalesce_parent_def]). *)
Definition coalesce_parent (x : N) : RA N := Fix N_lt_wf (fun _ => RA N) coalesce_parent_F x.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "coalesce_parent_def" *)
Theorem coalesce_parent_def : forall x,
  coalesce_parent x =
  (xt <- coalesced_sub x ;;
   bx <- is_Fixed xt ;;
   if bx then st_ex_return xt
   else if x <=? xt then st_ex_return x
   else
     anc <- coalesce_parent xt ;;
     update_coalesced x anc ;;
     st_ex_return anc).
Proof.
  intros x; unfold coalesce_parent at 1; rewrite Fix_eq.
  - unfold coalesce_parent_F; f_equal; apply functional_extensionality; intros xt.
    f_equal; apply functional_extensionality; intros [|]; [reflexivity|].
    destruct (Sumbool.sumbool_of_bool (x <=? xt)) as [E|E]; rewrite E; reflexivity.
  - intros y f g Hfg; assert (f = g) as ->; [|reflexivity].
    do 2 (apply functional_extensionality_dep; intros); apply Hfg.
Qed.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "canonize_move_def" *)
Definition canonize_move (x y : N) : RA (N * N) :=
  bx <- is_Fixed x ;;
  by_ <- is_Fixed y ;;
  if by_ then st_ex_return (y, x)
  else if bx then st_ex_return (x, y)
  else if x <? y then st_ex_return (x, y)
  else st_ex_return (y, x).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_FIRST_def" *)
(** HOL's move priority component is a type variable ['a]; here it is
    [N] (the only instance used by the compiler), because the committed
    statements in [reg_allocProof] (heuristics.v) quantify over the move list
    without a type annotation and would no longer elaborate. *)
Fixpoint st_ex_FIRST {B} (P : N -> N -> RA bool) (Q : N -> N -> RA (option B))
    (l : list (N * (N * N))) (unavail : list (N * (N * N)))
    : RA (option ((N * N) * (B * list (N * (N * N)))) * list (N * (N * N))) :=
  match l with
  | [] => st_ex_return (None, unavail)
  | m :: ms =>
      let '(p, (x, y)) := m in
      x <- coalesce_parent x ;;
      y <- coalesce_parent y ;;
      b1 <- P x y ;;
      if negb b1 then st_ex_FIRST P Q ms unavail
      else
        '(x, y) <- canonize_move x y ;;
        optb2 <- Q x y ;;
        match optb2 with
        | None => st_ex_FIRST P Q ms ((p, (x, y)) :: unavail)
        | Some pr => st_ex_return (Some ((x, y), (pr, ms)), unavail)
        end
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "respill_def" *)
Definition respill (k x : N) : RA unit :=
  xd <- degrees_sub x ;;
  if xd <? k then st_ex_return tt
  else
    freeze <- get_freeze_wl ;;
    if MEM x freeze then
      add_spill_wl [x] ;;
      set_freeze_wl (FILTER (fun y => negb (y =? x)) freeze)
    else st_ex_return tt.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_coalesce_def" *)
Definition do_coalesce (k : N) : RA bool :=
  am <- get_avail_moves_wl ;;
  '(ores, unavail) <- st_ex_FIRST consistency_ok (bg_ok k) am [] ;;
  add_unavail_moves_wl unavail ;;
  match ores with
  | None =>
      set_avail_moves_wl [] ;;
      st_ex_return false
  | Some ((x, y), ((case1, case2), ms)) =>
      set_avail_moves_wl ms ;;
      do_coalesce_real x y case1 case2 ;;
      unspill k ;;
      respill k x ;;
      st_ex_return true
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "reset_move_related_def" *)
(** HOL's move priority component is a type variable ['a]; here it is
    [N] (the only instance used by the compiler), because the committed
    statements in [reg_allocProof] (heuristics.v) quantify over the move list
    without a type annotation and would no longer elaborate. *)
Definition reset_move_related (ls : list (N * (N * N))) : RA unit :=
  d <- get_dim ;;
  st_ex_FOREACH (COUNT_LIST d) (fun x => update_move_related x false) ;;
  st_ex_FOREACH ls (fun '(_, (x, y)) =>
    bx <- is_Fixed x ;;
    by_ <- is_Fixed y ;;
    update_move_related x (negb bx) ;;
    update_move_related y (negb by_)).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_prefreeze_def" *)
Definition do_prefreeze (k : N) : RA bool :=
  fwl_pre <- get_freeze_wl ;;
  fwl <- st_ex_FILTER is_not_coalesced fwl_pre [] ;;
  swl_pre <- get_spill_wl ;;
  swl <- st_ex_FILTER is_not_coalesced swl_pre [] ;;
  set_spill_wl swl ;;
  uam_pre <- get_unavail_moves_wl ;;
  uam <- st_ex_FILTER (fun '(_, (x, y)) => consistency_ok x y) uam_pre [] ;;
  reset_move_related uam ;;
  uam <- set_unavail_moves_wl uam ;;
  '(ltkfreeze, ltksimp) <- st_ex_PARTITION move_related_sub fwl [] [] ;;
  add_simp_wl ltksimp ;;
  set_freeze_wl ltkfreeze ;;
  do_simplify k.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_freeze_def" *)
Definition do_freeze (k : N) : RA bool :=
  freeze <- get_freeze_wl ;;
  match freeze with
  | [] => st_ex_return false
  | x :: xs =>
      dec_degree x ;;
      push_stack x ;;
      set_freeze_wl xs ;;
      unspill k ;;
      st_ex_return true
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "safe_div_def" *)
Definition safe_div (x v : N) : N := if v =? 0 then 0 else x DIV v.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_list_MIN_cost_def" *)
Fixpoint st_ex_list_MIN_cost (scost : num_map N) (l : list N) (d k v : N) (acc : list N)
    : RA (N * list N) :=
  match l with
  | [] => st_ex_return (k, acc)
  | x :: xs =>
      if x <? d then
        xv <- degrees_sub x ;;
        cost <- st_ex_return (safe_div (lookup_any x scost 0) xv) ;;
        if cost <? v then st_ex_list_MIN_cost scost xs d x cost (k :: acc)
        else st_ex_list_MIN_cost scost xs d k v (x :: acc)
      else st_ex_list_MIN_cost scost xs d k v acc
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "st_ex_list_MAX_deg_def" *)
Fixpoint st_ex_list_MAX_deg (l : list N) (d k v : N) (acc : list N) : RA (N * list N) :=
  match l with
  | [] => st_ex_return (k, acc)
  | x :: xs =>
      if x <? d then
        xv <- degrees_sub x ;;
        if v <? xv then st_ex_list_MAX_deg xs d x xv (k :: acc)
        else st_ex_list_MAX_deg xs d k v (x :: acc)
      else st_ex_list_MAX_deg xs d k v acc
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_spill_def" *)
Definition do_spill (scostopt : option (num_map N)) (k : N) : RA bool :=
  spills <- get_spill_wl ;;
  d <- get_dim ;;
  match spills with
  | [] => st_ex_return false
  | x :: xs =>
      xv <- degrees_sub x ;;
      '(y, ys) <-
        match scostopt with
        | None => st_ex_list_MAX_deg xs d x xv []
        | Some scost =>
            st_ex_list_MIN_cost scost xs d x (safe_div (lookup_any x scost 0) xv) []
        end ;;
      dec_degree y ;;
      push_stack y ;;
      set_spill_wl ys ;;
      unspill k ;;
      st_ex_return true
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_step_def" *)
Definition do_step (scost : option (num_map N)) (k : N) : RA bool :=
  b <- do_simplify k ;;
  if b then st_ex_return b
  else
    b <- do_coalesce k ;;
    if b then st_ex_return b
    else
      b <- do_prefreeze k ;;
      if b then st_ex_return b
      else
        b <- do_freeze k ;;
        if b then st_ex_return b
        else
          b <- do_spill scost k ;;
          st_ex_return b.

(** HOL [rpt_do_step] (see [rpt_do_step_def]). *)
Definition rpt_do_step (scost : option (num_map N)) (k c : N) : RA unit :=
  num_rec (st_ex_return tt)
    (fun _ r => b <- do_step scost k ;; if b then r else st_ex_return tt) c.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "rpt_do_step_def" *)
Theorem rpt_do_step_def : forall scost k c,
  rpt_do_step scost k 0 = st_ex_return tt /\
  rpt_do_step scost k (SUC c) =
    (b <- do_step scost k ;; if b then rpt_do_step scost k c else st_ex_return tt).
Proof. intros; split; [reflexivity|unfold rpt_do_step; rewrite num_rec_SUC; reflexivity]. Qed.

(** ** The colouring functions *)

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "remove_colours_def" *)
Fixpoint remove_colours (ls : list N) (ks : list N) : RA (list N) :=
  match ls, ks with
  | _, [] => st_ex_return []
  | [], _ => st_ex_return ks
  | x :: xs, _ =>
      cx <- node_tag_sub x ;;
      r <- match cx with
           | Fixed c => remove_colours xs (FILTER (fun x => negb (x =? c)) ks)
           | _ => remove_colours xs ks
           end ;;
      st_ex_return r
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "assign_Atemp_tag_def" *)
Definition assign_Atemp_tag (ks : list N) (prefs : N -> list N -> RA (option N)) (n : N)
    : RA unit :=
  ntag <- node_tag_sub n ;;
  match ntag with
  | Atemp =>
      adjs <- adj_ls_sub n ;;
      ks <- remove_colours adjs ks ;;
      match ks with
      | [] => update_node_tag n Stemp
      | x :: _ =>
          c <- prefs n ks ;;
          match c with
          | None => update_node_tag n (Fixed x)
          | Some y => update_node_tag n (Fixed y)
          end
      end
  | _ => st_ex_return tt
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "assign_Atemps_def" *)
Definition assign_Atemps (k : N) (ls : list N) (prefs : N -> list N -> RA (option N))
    : RA unit :=
  d <- get_dim ;;
  ls <- st_ex_return (FILTER (fun n => n <? d) ls) ;;
  ks <- st_ex_return (GENLIST (fun x => x) k) ;;
  cs <- st_ex_return (GENLIST (fun x => x) d) ;;
  st_ex_FOREACH ls (assign_Atemp_tag ks prefs) ;;
  st_ex_FOREACH cs (assign_Atemp_tag ks prefs).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "tag_col_def" *)
Definition tag_col (t : tag) : N := match t with Fixed n => n | _ => 0 end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "unbound_colour_def" *)
Fixpoint unbound_colour (col : N) (l : list N) : N :=
  match l with
  | [] => col
  | x :: xs =>
      if col <? x then col
      else if x =? col then unbound_colour (col + 1) xs
      else unbound_colour col xs
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "assign_Stemp_tag_def" *)
Definition assign_Stemp_tag (k : N) (prefs : N -> list N -> RA (option N)) (n : N) : RA unit :=
  ntag <- node_tag_sub n ;;
  match ntag with
  | Stemp =>
      adjs <- adj_ls_sub n ;;
      tags <- st_ex_MAP node_tag_sub adjs ;;
      let bads := sort (fun x y => x <=? y) (MAP tag_col tags) in
      c <- prefs n bads ;;
      match c with
      | None => update_node_tag n (Fixed (unbound_colour k bads))
      | Some y => update_node_tag n (Fixed y)
      end
  | _ => st_ex_return tt
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "assign_Stemps_def" *)
Definition assign_Stemps (k : N) (prefs : N -> list N -> RA (option N)) : RA unit :=
  d <- get_dim ;;
  cs <- st_ex_return (GENLIST (fun x => x) d) ;;
  st_ex_FOREACH cs (assign_Stemp_tag k prefs).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "first_match_col_def" *)
Fixpoint first_match_col (ks : list N) (l : list N) : RA (option N) :=
  match l with
  | [] => st_ex_return None
  | x :: xs =>
      c <- node_tag_sub x ;;
      match c with
      | Fixed m => if MEM m ks then st_ex_return (Some m) else first_match_col ks xs
      | _ => first_match_col ks xs
      end
  end.

(** ** Clash trees *)

(** HOL's constructor [Set] is [Set_] ([Set] is a Rocq keyword). *)
(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "clash_tree" *)
Inductive clash_tree : Type :=
| Delta : list N -> list N -> clash_tree
| Set_ : num_set -> clash_tree
| Branch : option num_set -> clash_tree -> clash_tree -> clash_tree
| Seq : clash_tree -> clash_tree -> clash_tree.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "numset_list_delete_def" *)
Fixpoint numset_list_delete {A} (l : list N) (t : num_map A) : num_map A :=
  match l with
  | [] => t
  | x :: xs => numset_list_delete xs (delete x t)
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "check_col_def" *)
Definition check_col {A} (f : N -> N) (t : num_map A) : option (num_map A * num_set) :=
  let names := MAP (fun x => f (FST x)) (toAList t) in
  if ALL_DISTINCT names then Some (t, fromAList (MAP (fun x => (x, tt)) names))
  else None.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "check_partial_col_def" *)
Fixpoint check_partial_col (f : N -> N) (l : list N) (t ft : num_set)
    : option (num_set * num_set) :=
  match l with
  | [] => Some (t, ft)
  | x :: xs =>
      match lookup x t with
      | Some tt => check_partial_col f xs t ft
      | None =>
          match lookup (f x) ft with
          | None => check_partial_col f xs (insert x tt t) (insert (f x) tt ft)
          | Some tt => None
          end
      end
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "check_clash_tree_def" *)
Fixpoint check_clash_tree (f : N -> N) (ct : clash_tree) (live flive : num_set)
    : option (num_set * num_set) :=
  match ct with
  | Delta w r =>
      match check_partial_col f w live flive with
      | None => None
      | Some _ =>
          let del_w := numset_list_delete w live in
          let fdel_w := numset_list_delete (MAP f w) flive in
          check_partial_col f r del_w fdel_w
      end
  | Set_ t => check_col f t
  | Branch topt t1 t2 =>
      match check_clash_tree f t1 live flive with
      | None => None
      | Some (t1_out, ft1_out) =>
          match check_clash_tree f t2 live flive with
          | None => None
          | Some (t2_out, ft2_out) =>
              match topt with
              | None =>
                  check_partial_col f (MAP FST (toAList (difference t2_out t1_out)))
                    t1_out ft1_out
              | Some t => check_col f t
              end
          end
      end
  | Seq t1 t2 =>
      match check_clash_tree f t2 live flive with
      | None => None
      | Some (t2_out, ft2_out) => check_clash_tree f t1 t2_out ft2_out
      end
  end.

(** HOL's [(ta, fa, nv)] is the right-nested [(ta, (fa, nv))]. *)
(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "list_remap_def" *)
Fixpoint list_remap (l : list N) (tfn : num_map N * (num_map N * N))
    : num_map N * (num_map N * N) :=
  let '(ta, (fa, nv)) := tfn in
  match l with
  | [] => (ta, (fa, nv))
  | x :: xs =>
      match lookup x ta with
      | Some v => list_remap xs (ta, (fa, nv))
      | None => list_remap xs (insert x nv ta, (insert nv x fa, nv + 1))
      end
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "mk_bij_aux_def" *)
Fixpoint mk_bij_aux (ct : clash_tree) (tfn : num_map N * (num_map N * N))
    : num_map N * (num_map N * N) :=
  match ct with
  | Delta writes reads => list_remap writes (list_remap reads tfn)
  | Set_ t => list_remap (MAP FST (toAList t)) tfn
  | Branch topt t1 t2 =>
      let tfn' := mk_bij_aux t2 (mk_bij_aux t1 tfn) in
      match topt with
      | None => tfn'
      | Some ts => list_remap (MAP FST (toAList ts)) tfn'
      end
  | Seq t1 t2 => mk_bij_aux t1 (mk_bij_aux t2 tfn)
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "mk_bij_def" *)
Definition mk_bij (t : clash_tree) : num_map N * (num_map N * N) :=
  let '(ta, (fa, n)) := mk_bij_aux t (LN, (LN, 0)) in
  (ta, (fa, n)).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_stack_var_def" *)
Definition is_stack_var (n : N) : bool := n MOD 4 =? 3.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_phy_var_def" *)
Definition is_phy_var (n : N) : bool := n MOD 2 =? 0.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "is_alloc_var_def" *)
Definition is_alloc_var (n : N) : bool := n MOD 4 =? 1.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "mk_tags_def" *)
Definition mk_tags (n : N) (fs : num_set) (fa : N -> N) : RA unit :=
  inds <- st_ex_return (GENLIST (fun x => x) n) ;;
  st_ex_FOREACH inds (fun i =>
    let v := fa i in
    let remainder := v MOD 4 in
    if remainder =? 1 then
      match lookup v fs with
      | None => update_node_tag i Atemp
      | Some tt => update_node_tag i Stemp
      end
    else if remainder =? 3 then update_node_tag i Stemp
    else update_node_tag i (Fixed (v DIV 2))).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "mk_graph_def" *)
Fixpoint mk_graph (ta : N -> N) (ct : clash_tree) (liveout : list N) : RA (list N) :=
  match ct with
  | Delta w r =>
      wta <- st_ex_return (MAP ta w) ;;
      rta <- st_ex_return (MAP ta r) ;;
      live <- extend_clique wta liveout ;;
      live <- st_ex_return (FILTER (fun x => negb (MEM x wta)) live) ;;
      livein <- extend_clique rta live ;;
      st_ex_return livein
  | Set_ t =>
      live <- st_ex_return (MAP ta (MAP FST (toAList t))) ;;
      clique_insert_edge live ;;
      st_ex_return live
  | Branch topt t1 t2 =>
      t1_live <- mk_graph ta t1 liveout ;;
      t2_live <- mk_graph ta t2 liveout ;;
      match topt with
      | None =>
          livein <- extend_clique t1_live t2_live ;;
          st_ex_return livein
      | Some t =>
          clashes <- st_ex_return (MAP ta (MAP FST (toAList t))) ;;
          clique_insert_edge clashes ;;
          st_ex_return clashes
      end
  | Seq t1 t2 =>
      live <- mk_graph ta t2 liveout ;;
      mk_graph ta t1 live
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "sp_default_def" *)
Definition sp_default (t : num_map N) (i : N) : N :=
  match lookup i t with
  | None => if is_phy_var i then i DIV 2 else 0
  | Some x => x
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "extend_graph_def" *)
Fixpoint extend_graph {A} (ta : A -> N) (l : list (A * A)) : RA unit :=
  match l with
  | [] => st_ex_return tt
  | (x, y) :: xs => insert_edge (ta x) (ta y) ;; extend_graph ta xs
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "init_ra_state_def" *)
Definition init_ra_state (ct : clash_tree) (forced : list (N * N)) (fs : num_set)
    (tfn : num_map N * (num_map N * N)) : RA unit :=
  let '(ta, (fa, n)) := tfn in
  mk_graph (sp_default ta) ct [] ;;
  extend_graph (sp_default ta) forced ;;
  mk_tags n fs (sp_default fa).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_upd_coalesce_def" *)
Definition do_upd_coalesce (i : N) : RA unit := update_coalesced i (0 + i).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "init_alloc1_heu_def" *)
Definition init_alloc1_heu (moves : list (N * (N * N))) (d k : N) : RA N :=
  ds <- st_ex_return (COUNT_LIST d) ;;
  allocs <- st_ex_FILTER is_Atemp ds [] ;;
  st_ex_FOREACH ds (fun i =>
    adjls <- adj_ls_sub i ;;
    fills <- st_ex_FILTER (fun v => considered_var k v) adjls [] ;;
    update_degrees i (LENGTH fills)) ;;
  st_ex_FOREACH ds do_upd_coalesce ;;
  set_avail_moves_wl (sort_moves moves) ;;
  reset_move_related moves ;;
  '(ltk, gtk) <- st_ex_PARTITION (split_degree d k) allocs [] [] ;;
  '(ltkfreeze, ltksimp) <- st_ex_PARTITION move_related_sub ltk [] [] ;;
  set_spill_wl gtk ;;
  set_simp_wl ltksimp ;;
  set_freeze_wl ltkfreeze ;;
  st_ex_return (LENGTH allocs).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_alloc1_def" *)
Definition do_alloc1 (moves : list (N * (N * N))) (scost : option (num_map N)) (k : N)
    : RA (list N) :=
  d <- get_dim ;;
  l <- init_alloc1_heu moves d k ;;
  rpt_do_step scost k l ;;
  st <- get_stack ;;
  st_ex_return st.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "extract_tag_def" *)
Definition extract_tag (t : tag) : N := match t with Fixed m => m | _ => 0 end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "extract_color_def" *)
Definition extract_color (ta : num_map N) : RA (num_map N) :=
  taa <- st_ex_return (toAList ta) ;;
  itags <- st_ex_MAP (fun '(k, v) =>
    t <- node_tag_sub v ;;
    st_ex_return (k, extract_tag t)) taa ;;
  st_ex_return (fromAList itags).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "pri_move_insert_def" *)
Definition pri_move_insert {A B} (p : A) (x : N) (y : B) (acc : num_map (list (A * B)))
    : num_map (list (A * B)) :=
  match lookup x acc with
  | None => insert x [(p, y)] acc
  | Some ls => insert x ((p, y) :: ls) acc
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "undir_move_insert_def" *)
Definition undir_move_insert {A} (p : A) (x y : N) (acc : num_map (list (A * N)))
    : num_map (list (A * N)) :=
  pri_move_insert p x y (pri_move_insert p y x acc).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "moves_to_sp_def" *)
Fixpoint moves_to_sp {A} (l : list (A * (N * N))) (acc : num_map (list (A * N)))
    : num_map (list (A * N)) :=
  match l with
  | [] => acc
  | move :: xs =>
      let '(p, (x, y)) := move in
      moves_to_sp xs (undir_move_insert p x y acc)
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "resort_moves_def" *)
Definition resort_moves {A} (acc : num_map (list (N * A))) : num_map (list A) :=
  sptree.map (fun ls => MAP SND (sort_moves ls)) acc.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "algorithm" *)
Inductive algorithm : Type := Simple | IRC.

#[global] Instance algorithm_eq_dec : EqDecision algorithm.
Proof. intros [|] [|]; (left; reflexivity) || (right; discriminate). Defined.

Lemma coalesce_root_dec (x xt : N) : (x <=? xt) = false -> xt < x.
Proof. intros H; apply N.leb_gt, H. Qed.

Definition coalesce_root_F (x : N) (rec : forall y, y < x -> RA N) : RA N :=
  xt <- coalesced_sub x ;;
  bx <- is_Fixed xt ;;
  if bx then st_ex_return xt
  else
    match Sumbool.sumbool_of_bool (x <=? xt) with
    | left _ => st_ex_return x
    | right H => rec xt (coalesce_root_dec x xt H)
    end.

(** HOL [coalesce_root] (see [coalesce_root_def]). *)
Definition coalesce_root (x : N) : RA N := Fix N_lt_wf (fun _ => RA N) coalesce_root_F x.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "coalesce_root_def" *)
Theorem coalesce_root_def : forall x,
  coalesce_root x =
  (xt <- coalesced_sub x ;;
   bx <- is_Fixed xt ;;
   if bx then st_ex_return xt
   else if x <=? xt then st_ex_return x
   else coalesce_root xt).
Proof.
  intros x; unfold coalesce_root at 1; rewrite Fix_eq.
  - unfold coalesce_root_F; f_equal; apply functional_extensionality; intros xt.
    f_equal; apply functional_extensionality; intros [|]; [reflexivity|].
    destruct (Sumbool.sumbool_of_bool (x <=? xt)) as [E|E]; rewrite E; reflexivity.
  - intros y f g Hfg; assert (f = g) as ->; [|reflexivity].
    do 2 (apply functional_extensionality_dep; intros); apply Hfg.
Qed.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "biased_pref_def" *)
Definition biased_pref (mtable : num_map (list N)) (n : N) (ks : list N) : RA (option N) :=
  d <- get_dim ;;
  if n <? d then
    v <- coalesce_root n ;;
    let vs := match lookup n mtable with None => [] | Some vs => vs end in
    handle_Subscript (first_match_col ks (v :: vs)) (st_ex_return None)
  else st_ex_return None.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "full_consistency_ok_def" *)
Definition full_consistency_ok (k x y : N) : RA bool :=
  if x =? y then st_ex_return false
  else
    d <- get_dim ;;
    if (d <=? x) || (d <=? y) then st_ex_return false
    else
      adjy <- adj_ls_sub y ;;
      if sorted_mem x adjy then st_ex_return false
      else
        bx <- is_Fixed_k k x ;;
        by_ <- is_Fixed_k k y ;;
        ax <- is_Atemp x ;;
        ay <- is_Atemp y ;;
        st_ex_return ((bx || ax) && (by_ || ay) && negb (bx && by_)).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "update_move_def" *)
Definition update_move (spta : N -> N) (m : N * (N * N)) : N * (N * N) :=
  let '(p, (x, y)) := m in
  let spx := spta x in
  let spy := spta y in
  if spx <=? spy then (p, (spx, spy)) else (p, (spy, spx)).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "neg_first_match_col_def" *)
Fixpoint neg_first_match_col (k : N) (bads : list N) (l : list N) : RA (option N) :=
  match l with
  | [] => st_ex_return None
  | x :: xs =>
      c <- node_tag_sub x ;;
      match c with
      | Fixed m =>
          if MEM m bads || (m <? k) then neg_first_match_col k bads xs
          else st_ex_return (Some m)
      | _ => neg_first_match_col k bads xs
      end
  end.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "neg_biased_pref_def" *)
Definition neg_biased_pref (k : N) (mtable : num_map (list N)) (n : N) (bads : list N)
    : RA (option N) :=
  d <- get_dim ;;
  if n <? d then
    let vs := match lookup n mtable with None => [] | Some vs => vs end in
    handle_Subscript (neg_first_match_col k bads vs) (st_ex_return None)
  else st_ex_return None.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "do_reg_alloc_def" *)
Definition do_reg_alloc (alg : algorithm) (scost : option (num_map N)) (k : N)
    (moves : list (N * (N * N))) (ct : clash_tree) (forced : list (N * N)) (fs : num_set)
    (tfn : num_map N * (num_map N * N)) : RA (num_map N) :=
  let '(ta, (fa, n)) := tfn in
  init_ra_state ct forced fs (ta, (fa, n)) ;;
  moves0 <- st_ex_return (MAP (update_move (sp_default ta)) moves) ;;
  moves <- st_ex_FILTER (fun '(_, (x, y)) => full_consistency_ok k x y) moves0 [] ;;
  ls <- do_alloc1 (if bool_decide (alg = Simple) then [] else moves) scost k ;;
  mvs <- st_ex_return (resort_moves (moves_to_sp moves0 LN)) ;;
  assign_Atemps k ls (biased_pref mvs) ;;
  assign_Stemps k (neg_biased_pref k mvs) ;;
  spcol <- extract_color ta ;;
  st_ex_return spcol.

(** ** Running the allocator *)

(** Generated by HOL's [define_run ``:ra_state`` [...] "ira_state"]: the
    array fields hold [(size, initial value)]; field names are prefixed with
    [ira_state_] (they would clash with [ra_state]'s). *)
Record ira_state : Type := mk_ira_state {
  ira_state_adj_ls : N * list N;
  ira_state_node_tag : N * tag;
  ira_state_degrees : N * N;
  ira_state_dim : N;
  ira_state_simp_wl : list N;
  ira_state_spill_wl : list N;
  ira_state_freeze_wl : list N;
  ira_state_avail_moves_wl : list (N * (N * N));
  ira_state_unavail_moves_wl : list (N * (N * N));
  ira_state_coalesced : N * N;
  ira_state_move_related : N * bool;
  ira_state_stack : list N
}.

(** Generated by HOL's [define_run] (HOL's [run_ira_state_def]). *)
(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "run_ira_state_def" *)
Definition run_ira_state {A E} (x : M ra_state A E) (state : ira_state) : exc A E :=
  run x (mk_ra_state
    (marray_replicate (FST state.(ira_state_adj_ls)) (SND state.(ira_state_adj_ls)))
    (marray_replicate (FST state.(ira_state_node_tag)) (SND state.(ira_state_node_tag)))
    (marray_replicate (FST state.(ira_state_degrees)) (SND state.(ira_state_degrees)))
    state.(ira_state_dim)
    state.(ira_state_simp_wl)
    state.(ira_state_spill_wl)
    state.(ira_state_freeze_wl)
    state.(ira_state_avail_moves_wl)
    state.(ira_state_unavail_moves_wl)
    (marray_replicate (FST state.(ira_state_coalesced)) (SND state.(ira_state_coalesced)))
    (marray_replicate (FST state.(ira_state_move_related)) (SND state.(ira_state_move_related)))
    state.(ira_state_stack)).

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "reg_alloc_aux_def" *)
Definition reg_alloc_aux (alg : algorithm) (scost : option (num_map N)) (k : N)
    (moves : list (N * (N * N))) (ct : clash_tree) (forced : list (N * N)) (fs : num_set)
    (tfn : num_map N * (num_map N * N)) : exc (num_map N) state_exn :=
  let '(ta, (fa, n)) := tfn in
  run_ira_state (do_reg_alloc alg scost k moves ct forced fs (ta, (fa, n)))
    {| ira_state_adj_ls := (n, []);
       ira_state_node_tag := (n, Atemp);
       ira_state_degrees := (n, 0);
       ira_state_dim := n;
       ira_state_simp_wl := [];
       ira_state_spill_wl := [];
       ira_state_freeze_wl := [];
       ira_state_avail_moves_wl := [];
       ira_state_unavail_moves_wl := [];
       ira_state_coalesced := (n, 0);
       ira_state_move_related := (n, false);
       ira_state_stack := [] |}.

(*! HOL "cakeml/compiler/backend/reg_alloc/reg_allocScript.sml" "reg_alloc_def" *)
Definition reg_alloc (alg : algorithm) (scost : option (num_map N)) (k : N)
    (moves : list (N * (N * N))) (ct : clash_tree) (forced : list (N * N)) (fs : num_set)
    : exc (num_map N) state_exn :=
  reg_alloc_aux alg scost k moves ct forced fs (mk_bij ct).
