(** * HOL4 L3 RISC-V model [riscv] (generated by L3)

    Port of [HOL/examples/l3-machine-code/riscv/model/riscvScript.sml], which
    is itself generated by L3 through the [Import] library
    ([HOL/examples/l3-machine-code/common/Import.sml]).  This file was
    produced mechanically from the L3 source terms; the translation is:

    - [Construct [(t, cs)]] (an algebraic datatype) is an [Inductive];
      [Record (t, fs)] is a Rocq [Record] whose fields carry the names of
      HOL's accessor constants [t_f] (e.g. [riscv_state_c_PC]).  HOL type
      names that are also constructor names ([ArithI], [Branch], [Load], ...)
      get the suffix [_ty]; constructors keep their HOL names.
    - [FTy n] / [F8] ... is [word n]; [PTy (a, b)] is [a * b]: an L3 tuple
      [a # b # c] is the Rocq tuple [a * b * c] (written and matched as
      [(x, y, z)] on both sides; only whole tuples are ever matched).
    - [Def (f, TP [x; y], e)] is [Definition f '((x, y) : ...) := e].
    - [LW (i, n)] is [n2w i : word n]; [EX (x, h, l, ty)] is
      [(h >< l) x : ty]; [CC [x; ...; y]] is [x @@ ... @@ y];
      [Bop (Bit, x, n)] is [word_bit n x]; [Mop (Cast F1, b)] for a boolean
      [b] is HOL's [v2w [b] : word1] (bitstring theory, not yet ported),
      written here as [(if b then n2w 1 else n2w 0 : word1)], its value.
      The notations are those of [word_scope].  HOL infers the widths of
      [@@] operands and of intermediate concatenations (the sums of the
      operand widths); Rocq cannot, so they are written as ascriptions.

    The L3 declaration forms [Construct], [Record] are not recognised by
    [scripts/check-hol-refs.py] (only [val f_def = Def ...] is), so the
    datatypes carry no [HOL] tags; each says which HOL type it is.

    Ported so far: all datatypes and records (including [riscv_state]), and
    the instruction encoder [Encode] with its helpers ([opc], [amofunc],
    [Rtype], [R4type], [Itype], [Stype], [SBtype], [Utype], [UJtype]), which
    is what CakeML's RISC-V encoder ([riscv_target]) uses.

    Not yet ported (still to do): the state monad helpers
    ([raise'exception], CSR/register accessors, [archBase], ...), memory and
    translation ([translateAddr], TLB), the [dfn'*] instruction semantics,
    [Run], [Fetch], [Decode], [DecodeRVC], [EncodeRVC], [CBtype], [Next],
    the string assembler/disassembler functions ([pRtype], ...), and the
    derived [riscv_step] theory ([NextRISCV]) used by [riscv_target]'s
    [riscv_next]. *)

From Galette Require Import Base.
From Galette.HOL.src.n_bit Require Import words.
Open Scope N_scope.

(** ** Datatypes *)

(** HOL datatype [rawInstType] (L3 [Construct]). *)
Inductive rawInstType : Type :=
| Half : word16 -> rawInstType
| Word : word32 -> rawInstType
.
#[global] Instance rawInstType_inhabited : Inhabited rawInstType := Half (inhabitant _).

(** HOL datatype [accessType] (L3 [Construct]). *)
Inductive accessType : Type :=
| Read : accessType
| Write : accessType
.
#[global] Instance accessType_inhabited : Inhabited accessType := Read.

(** HOL datatype [fetchType] (L3 [Construct]). *)
Inductive fetchType : Type :=
| Instruction : fetchType
| Data : fetchType
.
#[global] Instance fetchType_inhabited : Inhabited fetchType := Instruction.

(** HOL datatype [Architecture] (L3 [Construct]). *)
Inductive Architecture : Type :=
| RV32I : Architecture
| RV64I : Architecture
| RV128I : Architecture
.
#[global] Instance Architecture_inhabited : Inhabited Architecture := RV32I.

(** HOL datatype [Privilege] (L3 [Construct]). *)
Inductive Privilege : Type :=
| User : Privilege
| Supervisor : Privilege
| Hypervisor : Privilege
| Machine : Privilege
.
#[global] Instance Privilege_inhabited : Inhabited Privilege := User.

(** HOL datatype [VM_Mode] (L3 [Construct]). *)
Inductive VM_Mode : Type :=
| Mbare : VM_Mode
| Mbb : VM_Mode
| Mbbid : VM_Mode
| Sv32 : VM_Mode
| Sv39 : VM_Mode
| Sv48 : VM_Mode
| Sv57 : VM_Mode
| Sv64 : VM_Mode
.
#[global] Instance VM_Mode_inhabited : Inhabited VM_Mode := Mbare.

(** HOL datatype [ExtStatus] (L3 [Construct]). *)
Inductive ExtStatus : Type :=
| Off : ExtStatus
| Initial : ExtStatus
| Clean : ExtStatus
| Dirty : ExtStatus
.
#[global] Instance ExtStatus_inhabited : Inhabited ExtStatus := Off.

(** HOL datatype [Interrupt] (L3 [Construct]). *)
Inductive Interrupt : Type :=
| Software : Interrupt
| Timer : Interrupt
.
#[global] Instance Interrupt_inhabited : Inhabited Interrupt := Software.

(** HOL datatype [ExceptionType] (L3 [Construct]). *)
Inductive ExceptionType : Type :=
| Fetch_Misaligned : ExceptionType
| Fetch_Fault : ExceptionType
| Illegal_Instr : ExceptionType
| Breakpoint : ExceptionType
| Load_Fault : ExceptionType
| AMO_Misaligned : ExceptionType
| Store_AMO_Fault : ExceptionType
| UMode_Env_Call : ExceptionType
| SMode_Env_Call : ExceptionType
| HMode_Env_Call : ExceptionType
| MMode_Env_Call : ExceptionType
.
#[global] Instance ExceptionType_inhabited : Inhabited ExceptionType := Fetch_Misaligned.

(** HOL record type [mcpuid] (L3 [Record]); fields are named after HOL's
    accessor constants [mcpuid_<field>]. *)
Record mcpuid : Type := {
  mcpuid_ArchBase : word2;
  mcpuid_I : bool;
  mcpuid_M : bool;
  mcpuid_S : bool;
  mcpuid_U : bool;
  mcpuid_mcpuid'rst : word 58
}.
#[global] Instance mcpuid_inhabited : Inhabited mcpuid :=
  {| mcpuid_ArchBase := inhabitant _;
     mcpuid_I := inhabitant _;
     mcpuid_M := inhabitant _;
     mcpuid_S := inhabitant _;
     mcpuid_U := inhabitant _;
     mcpuid_mcpuid'rst := inhabitant _ |}.

(** HOL record type [mimpid] (L3 [Record]); fields are named after HOL's
    accessor constants [mimpid_<field>]. *)
Record mimpid : Type := {
  mimpid_RVImpl : word 48;
  mimpid_RVSource : word16
}.
#[global] Instance mimpid_inhabited : Inhabited mimpid :=
  {| mimpid_RVImpl := inhabitant _;
     mimpid_RVSource := inhabitant _ |}.

(** HOL record type [mstatus] (L3 [Record]); fields are named after HOL's
    accessor constants [mstatus_<field>]. *)
Record mstatus : Type := {
  mstatus_MFS : word2;
  mstatus_MIE : bool;
  mstatus_MIE1 : bool;
  mstatus_MIE2 : bool;
  mstatus_MIE3 : bool;
  mstatus_MMPRV : bool;
  mstatus_MPRV : word2;
  mstatus_MPRV1 : word2;
  mstatus_MPRV2 : word2;
  mstatus_MPRV3 : word2;
  mstatus_MSD : bool;
  mstatus_MXS : word2;
  mstatus_VM : word5;
  mstatus_mstatus'rst : word 41
}.
#[global] Instance mstatus_inhabited : Inhabited mstatus :=
  {| mstatus_MFS := inhabitant _;
     mstatus_MIE := inhabitant _;
     mstatus_MIE1 := inhabitant _;
     mstatus_MIE2 := inhabitant _;
     mstatus_MIE3 := inhabitant _;
     mstatus_MMPRV := inhabitant _;
     mstatus_MPRV := inhabitant _;
     mstatus_MPRV1 := inhabitant _;
     mstatus_MPRV2 := inhabitant _;
     mstatus_MPRV3 := inhabitant _;
     mstatus_MSD := inhabitant _;
     mstatus_MXS := inhabitant _;
     mstatus_VM := inhabitant _;
     mstatus_mstatus'rst := inhabitant _ |}.

(** HOL record type [mtdeleg] (L3 [Record]); fields are named after HOL's
    accessor constants [mtdeleg_<field>]. *)
Record mtdeleg : Type := {
  mtdeleg_Exc_deleg : word16;
  mtdeleg_Intr_deleg : word 48
}.
#[global] Instance mtdeleg_inhabited : Inhabited mtdeleg :=
  {| mtdeleg_Exc_deleg := inhabitant _;
     mtdeleg_Intr_deleg := inhabitant _ |}.

(** HOL record type [mip] (L3 [Record]); fields are named after HOL's
    accessor constants [mip_<field>]. *)
Record mip : Type := {
  mip_HSIP : bool;
  mip_HTIP : bool;
  mip_MSIP : bool;
  mip_MTIP : bool;
  mip_SSIP : bool;
  mip_STIP : bool;
  mip_mip'rst : word 58
}.
#[global] Instance mip_inhabited : Inhabited mip :=
  {| mip_HSIP := inhabitant _;
     mip_HTIP := inhabitant _;
     mip_MSIP := inhabitant _;
     mip_MTIP := inhabitant _;
     mip_SSIP := inhabitant _;
     mip_STIP := inhabitant _;
     mip_mip'rst := inhabitant _ |}.

(** HOL record type [mie] (L3 [Record]); fields are named after HOL's
    accessor constants [mie_<field>]. *)
Record mie : Type := {
  mie_HSIE : bool;
  mie_HTIE : bool;
  mie_MSIE : bool;
  mie_MTIE : bool;
  mie_SSIE : bool;
  mie_STIE : bool;
  mie_mie'rst : word 58
}.
#[global] Instance mie_inhabited : Inhabited mie :=
  {| mie_HSIE := inhabitant _;
     mie_HTIE := inhabitant _;
     mie_MSIE := inhabitant _;
     mie_MTIE := inhabitant _;
     mie_SSIE := inhabitant _;
     mie_STIE := inhabitant _;
     mie_mie'rst := inhabitant _ |}.

(** HOL record type [mcause] (L3 [Record]); fields are named after HOL's
    accessor constants [mcause_<field>]. *)
Record mcause : Type := {
  mcause_EC : word4;
  mcause_Int : bool;
  mcause_mcause'rst : word 59
}.
#[global] Instance mcause_inhabited : Inhabited mcause :=
  {| mcause_EC := inhabitant _;
     mcause_Int := inhabitant _;
     mcause_mcause'rst := inhabitant _ |}.

(** HOL record type [MachineCSR] (L3 [Record]); fields are named after HOL's
    accessor constants [MachineCSR_<field>]. *)
Record MachineCSR : Type := {
  MachineCSR_mbadaddr : word64;
  MachineCSR_mbase : word64;
  MachineCSR_mbound : word64;
  MachineCSR_mcause : mcause;
  MachineCSR_mcpuid : mcpuid;
  MachineCSR_mdbase : word64;
  MachineCSR_mdbound : word64;
  MachineCSR_mepc : word64;
  MachineCSR_mfromhost : word64;
  MachineCSR_mhartid : word64;
  MachineCSR_mibase : word64;
  MachineCSR_mibound : word64;
  MachineCSR_mie : mie;
  MachineCSR_mimpid : mimpid;
  MachineCSR_mip : mip;
  MachineCSR_mscratch : word64;
  MachineCSR_mstatus : mstatus;
  MachineCSR_mtdeleg : mtdeleg;
  MachineCSR_mtime_delta : word64;
  MachineCSR_mtimecmp : word64;
  MachineCSR_mtohost : word64;
  MachineCSR_mtvec : word64
}.
#[global] Instance MachineCSR_inhabited : Inhabited MachineCSR :=
  {| MachineCSR_mbadaddr := inhabitant _;
     MachineCSR_mbase := inhabitant _;
     MachineCSR_mbound := inhabitant _;
     MachineCSR_mcause := inhabitant _;
     MachineCSR_mcpuid := inhabitant _;
     MachineCSR_mdbase := inhabitant _;
     MachineCSR_mdbound := inhabitant _;
     MachineCSR_mepc := inhabitant _;
     MachineCSR_mfromhost := inhabitant _;
     MachineCSR_mhartid := inhabitant _;
     MachineCSR_mibase := inhabitant _;
     MachineCSR_mibound := inhabitant _;
     MachineCSR_mie := inhabitant _;
     MachineCSR_mimpid := inhabitant _;
     MachineCSR_mip := inhabitant _;
     MachineCSR_mscratch := inhabitant _;
     MachineCSR_mstatus := inhabitant _;
     MachineCSR_mtdeleg := inhabitant _;
     MachineCSR_mtime_delta := inhabitant _;
     MachineCSR_mtimecmp := inhabitant _;
     MachineCSR_mtohost := inhabitant _;
     MachineCSR_mtvec := inhabitant _ |}.

(** HOL record type [HypervisorCSR] (L3 [Record]); fields are named after HOL's
    accessor constants [HypervisorCSR_<field>]. *)
Record HypervisorCSR : Type := {
  HypervisorCSR_hbadaddr : word64;
  HypervisorCSR_hcause : mcause;
  HypervisorCSR_hepc : word64;
  HypervisorCSR_hscratch : word64;
  HypervisorCSR_hstatus : mstatus;
  HypervisorCSR_htdeleg : mtdeleg;
  HypervisorCSR_htime_delta : word64;
  HypervisorCSR_htimecmp : word64;
  HypervisorCSR_htvec : word64
}.
#[global] Instance HypervisorCSR_inhabited : Inhabited HypervisorCSR :=
  {| HypervisorCSR_hbadaddr := inhabitant _;
     HypervisorCSR_hcause := inhabitant _;
     HypervisorCSR_hepc := inhabitant _;
     HypervisorCSR_hscratch := inhabitant _;
     HypervisorCSR_hstatus := inhabitant _;
     HypervisorCSR_htdeleg := inhabitant _;
     HypervisorCSR_htime_delta := inhabitant _;
     HypervisorCSR_htimecmp := inhabitant _;
     HypervisorCSR_htvec := inhabitant _ |}.

(** HOL record type [sstatus] (L3 [Record]); fields are named after HOL's
    accessor constants [sstatus_<field>]. *)
Record sstatus : Type := {
  sstatus_SFS : word2;
  sstatus_SIE : bool;
  sstatus_SMPRV : bool;
  sstatus_SPIE : bool;
  sstatus_SPS : bool;
  sstatus_SSD : bool;
  sstatus_SXS : word2;
  sstatus_sstatus'rst : word 55
}.
#[global] Instance sstatus_inhabited : Inhabited sstatus :=
  {| sstatus_SFS := inhabitant _;
     sstatus_SIE := inhabitant _;
     sstatus_SMPRV := inhabitant _;
     sstatus_SPIE := inhabitant _;
     sstatus_SPS := inhabitant _;
     sstatus_SSD := inhabitant _;
     sstatus_SXS := inhabitant _;
     sstatus_sstatus'rst := inhabitant _ |}.

(** HOL record type [sip] (L3 [Record]); fields are named after HOL's
    accessor constants [sip_<field>]. *)
Record sip : Type := {
  sip_SSIP : bool;
  sip_STIP : bool;
  sip_sip'rst : word 62
}.
#[global] Instance sip_inhabited : Inhabited sip :=
  {| sip_SSIP := inhabitant _;
     sip_STIP := inhabitant _;
     sip_sip'rst := inhabitant _ |}.

(** HOL record type [sie] (L3 [Record]); fields are named after HOL's
    accessor constants [sie_<field>]. *)
Record sie : Type := {
  sie_SSIE : bool;
  sie_STIE : bool;
  sie_sie'rst : word 62
}.
#[global] Instance sie_inhabited : Inhabited sie :=
  {| sie_SSIE := inhabitant _;
     sie_STIE := inhabitant _;
     sie_sie'rst := inhabitant _ |}.

(** HOL record type [SupervisorCSR] (L3 [Record]); fields are named after HOL's
    accessor constants [SupervisorCSR_<field>]. *)
Record SupervisorCSR : Type := {
  SupervisorCSR_sasid : word64;
  SupervisorCSR_sbadaddr : word64;
  SupervisorCSR_scause : mcause;
  SupervisorCSR_sepc : word64;
  SupervisorCSR_sptbr : word64;
  SupervisorCSR_sscratch : word64;
  SupervisorCSR_stime_delta : word64;
  SupervisorCSR_stimecmp : word64;
  SupervisorCSR_stvec : word64
}.
#[global] Instance SupervisorCSR_inhabited : Inhabited SupervisorCSR :=
  {| SupervisorCSR_sasid := inhabitant _;
     SupervisorCSR_sbadaddr := inhabitant _;
     SupervisorCSR_scause := inhabitant _;
     SupervisorCSR_sepc := inhabitant _;
     SupervisorCSR_sptbr := inhabitant _;
     SupervisorCSR_sscratch := inhabitant _;
     SupervisorCSR_stime_delta := inhabitant _;
     SupervisorCSR_stimecmp := inhabitant _;
     SupervisorCSR_stvec := inhabitant _ |}.

(** HOL record type [FPCSR] (L3 [Record]); fields are named after HOL's
    accessor constants [FPCSR_<field>]. *)
Record FPCSR : Type := {
  FPCSR_DZ : bool;
  FPCSR_FRM : word3;
  FPCSR_NV : bool;
  FPCSR_NX : bool;
  FPCSR_OF : bool;
  FPCSR_UF : bool;
  FPCSR_fpcsr'rst : word 24
}.
#[global] Instance FPCSR_inhabited : Inhabited FPCSR :=
  {| FPCSR_DZ := inhabitant _;
     FPCSR_FRM := inhabitant _;
     FPCSR_NV := inhabitant _;
     FPCSR_NX := inhabitant _;
     FPCSR_OF := inhabitant _;
     FPCSR_UF := inhabitant _;
     FPCSR_fpcsr'rst := inhabitant _ |}.

(** HOL record type [UserCSR] (L3 [Record]); fields are named after HOL's
    accessor constants [UserCSR_<field>]. *)
Record UserCSR : Type := {
  UserCSR_cycle_delta : word64;
  UserCSR_fpcsr : FPCSR;
  UserCSR_instret_delta : word64;
  UserCSR_time_delta : word64
}.
#[global] Instance UserCSR_inhabited : Inhabited UserCSR :=
  {| UserCSR_cycle_delta := inhabitant _;
     UserCSR_fpcsr := inhabitant _;
     UserCSR_instret_delta := inhabitant _;
     UserCSR_time_delta := inhabitant _ |}.

(** HOL record type [SynchronousTrap] (L3 [Record]); fields are named after HOL's
    accessor constants [SynchronousTrap_<field>]. *)
Record SynchronousTrap : Type := {
  SynchronousTrap_badaddr : option word64;
  SynchronousTrap_trap : ExceptionType
}.
#[global] Instance SynchronousTrap_inhabited : Inhabited SynchronousTrap :=
  {| SynchronousTrap_badaddr := inhabitant _;
     SynchronousTrap_trap := inhabitant _ |}.

(** HOL datatype [TransferControl] (L3 [Construct]). *)
Inductive TransferControl : Type :=
| BranchTo : word64 -> TransferControl
| Ereturn : TransferControl
| Mrts : TransferControl
| Trap : SynchronousTrap -> TransferControl
.
#[global] Instance TransferControl_inhabited : Inhabited TransferControl := BranchTo (inhabitant _).

(** HOL datatype [Rounding] (L3 [Construct]). *)
Inductive Rounding : Type :=
| RNE : Rounding
| RTZ : Rounding
| RDN : Rounding
| RUP : Rounding
| RMM : Rounding
| RDYN : Rounding
.
#[global] Instance Rounding_inhabited : Inhabited Rounding := RNE.

(** HOL record type [StateDelta] (L3 [Record]); fields are named after HOL's
    accessor constants [StateDelta_<field>]. *)
Record StateDelta : Type := {
  StateDelta_addr : option word64;
  StateDelta_data1 : option word64;
  StateDelta_data2 : option word64;
  StateDelta_exc_taken : bool;
  StateDelta_fetch_exc : bool;
  StateDelta_fp_data : option word64;
  StateDelta_pc : word64;
  StateDelta_rinstr : rawInstType;
  StateDelta_st_width : option word32
}.
#[global] Instance StateDelta_inhabited : Inhabited StateDelta :=
  {| StateDelta_addr := inhabitant _;
     StateDelta_data1 := inhabitant _;
     StateDelta_data2 := inhabitant _;
     StateDelta_exc_taken := inhabitant _;
     StateDelta_fetch_exc := inhabitant _;
     StateDelta_fp_data := inhabitant _;
     StateDelta_pc := inhabitant _;
     StateDelta_rinstr := inhabitant _;
     StateDelta_st_width := inhabitant _ |}.

(** HOL record type [SV_PTE] (L3 [Record]); fields are named after HOL's
    accessor constants [SV_PTE_<field>]. *)
Record SV_PTE : Type := {
  SV_PTE_PTE_D : bool;
  SV_PTE_PTE_PPNi : word 38;
  SV_PTE_PTE_R : bool;
  SV_PTE_PTE_SW : word3;
  SV_PTE_PTE_T : word4;
  SV_PTE_PTE_V : bool;
  SV_PTE_sv_pte'rst : word16
}.
#[global] Instance SV_PTE_inhabited : Inhabited SV_PTE :=
  {| SV_PTE_PTE_D := inhabitant _;
     SV_PTE_PTE_PPNi := inhabitant _;
     SV_PTE_PTE_R := inhabitant _;
     SV_PTE_PTE_SW := inhabitant _;
     SV_PTE_PTE_T := inhabitant _;
     SV_PTE_PTE_V := inhabitant _;
     SV_PTE_sv_pte'rst := inhabitant _ |}.

(** HOL record type [SV_Vaddr] (L3 [Record]); fields are named after HOL's
    accessor constants [SV_Vaddr_<field>]. *)
Record SV_Vaddr : Type := {
  SV_Vaddr_Sv_PgOfs : word12;
  SV_Vaddr_Sv_VPNi : word 36;
  SV_Vaddr_sv_vaddr'rst : word16
}.
#[global] Instance SV_Vaddr_inhabited : Inhabited SV_Vaddr :=
  {| SV_Vaddr_Sv_PgOfs := inhabitant _;
     SV_Vaddr_Sv_VPNi := inhabitant _;
     SV_Vaddr_sv_vaddr'rst := inhabitant _ |}.

(** HOL record type [TLBEntry] (L3 [Record]); fields are named after HOL's
    accessor constants [TLBEntry_<field>]. *)
Record TLBEntry : Type := {
  TLBEntry_age : word64;
  TLBEntry_asid : word6;
  TLBEntry_global : bool;
  TLBEntry_pAddr : word64;
  TLBEntry_pte : SV_PTE;
  TLBEntry_pteAddr : word64;
  TLBEntry_vAddr : word64;
  TLBEntry_vAddrMask : word64;
  TLBEntry_vMatchMask : word64
}.
#[global] Instance TLBEntry_inhabited : Inhabited TLBEntry :=
  {| TLBEntry_age := inhabitant _;
     TLBEntry_asid := inhabitant _;
     TLBEntry_global := inhabitant _;
     TLBEntry_pAddr := inhabitant _;
     TLBEntry_pte := inhabitant _;
     TLBEntry_pteAddr := inhabitant _;
     TLBEntry_vAddr := inhabitant _;
     TLBEntry_vAddrMask := inhabitant _;
     TLBEntry_vMatchMask := inhabitant _ |}.

(** HOL datatype [Internal] (L3 [Construct]). Its Rocq name is [Internal_ty]: HOL also has a constructor [Internal] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive Internal_ty : Type :=
| FETCH_FAULT : word64 -> Internal_ty
| FETCH_MISALIGNED : word64 -> Internal_ty
.
#[global] Instance Internal_ty_inhabited : Inhabited Internal_ty := FETCH_FAULT (inhabitant _).

(** HOL datatype [System] (L3 [Construct]). Its Rocq name is [System_ty]: HOL also has a constructor [System] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive System_ty : Type :=
| CSRRC : (word5 * word5 * word12) -> System_ty
| CSRRCI : (word5 * word5 * word12) -> System_ty
| CSRRS : (word5 * word5 * word12) -> System_ty
| CSRRSI : (word5 * word5 * word12) -> System_ty
| CSRRW : (word5 * word5 * word12) -> System_ty
| CSRRWI : (word5 * word5 * word12) -> System_ty
| EBREAK : System_ty
| ECALL : System_ty
| ERET : System_ty
| MRTS : System_ty
| SFENCE_VM : word5 -> System_ty
| WFI : System_ty
.
#[global] Instance System_ty_inhabited : Inhabited System_ty := CSRRC (inhabitant _).

(** HOL datatype [FConv] (L3 [Construct]). Its Rocq name is [FConv_ty]: HOL also has a constructor [FConv] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive FConv_ty : Type :=
| FCLASS_D : (word5 * word5) -> FConv_ty
| FCLASS_S : (word5 * word5) -> FConv_ty
| FCVT_D_L : (word5 * word5 * word3) -> FConv_ty
| FCVT_D_LU : (word5 * word5 * word3) -> FConv_ty
| FCVT_D_S : (word5 * word5 * word3) -> FConv_ty
| FCVT_D_W : (word5 * word5 * word3) -> FConv_ty
| FCVT_D_WU : (word5 * word5 * word3) -> FConv_ty
| FCVT_LU_D : (word5 * word5 * word3) -> FConv_ty
| FCVT_LU_S : (word5 * word5 * word3) -> FConv_ty
| FCVT_L_D : (word5 * word5 * word3) -> FConv_ty
| FCVT_L_S : (word5 * word5 * word3) -> FConv_ty
| FCVT_S_D : (word5 * word5 * word3) -> FConv_ty
| FCVT_S_L : (word5 * word5 * word3) -> FConv_ty
| FCVT_S_LU : (word5 * word5 * word3) -> FConv_ty
| FCVT_S_W : (word5 * word5 * word3) -> FConv_ty
| FCVT_S_WU : (word5 * word5 * word3) -> FConv_ty
| FCVT_WU_D : (word5 * word5 * word3) -> FConv_ty
| FCVT_WU_S : (word5 * word5 * word3) -> FConv_ty
| FCVT_W_D : (word5 * word5 * word3) -> FConv_ty
| FCVT_W_S : (word5 * word5 * word3) -> FConv_ty
| FMV_D_X : (word5 * word5) -> FConv_ty
| FMV_S_X : (word5 * word5) -> FConv_ty
| FMV_X_D : (word5 * word5) -> FConv_ty
| FMV_X_S : (word5 * word5) -> FConv_ty
| FSGNJN_D : (word5 * word5 * word5) -> FConv_ty
| FSGNJN_S : (word5 * word5 * word5) -> FConv_ty
| FSGNJX_D : (word5 * word5 * word5) -> FConv_ty
| FSGNJX_S : (word5 * word5 * word5) -> FConv_ty
| FSGNJ_D : (word5 * word5 * word5) -> FConv_ty
| FSGNJ_S : (word5 * word5 * word5) -> FConv_ty
.
#[global] Instance FConv_ty_inhabited : Inhabited FConv_ty := FCLASS_D (inhabitant _).

(** HOL datatype [FArith] (L3 [Construct]). Its Rocq name is [FArith_ty]: HOL also has a constructor [FArith] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive FArith_ty : Type :=
| FADD_D : (word5 * word5 * word5 * word3) -> FArith_ty
| FADD_S : (word5 * word5 * word5 * word3) -> FArith_ty
| FDIV_D : (word5 * word5 * word5 * word3) -> FArith_ty
| FDIV_S : (word5 * word5 * word5 * word3) -> FArith_ty
| FEQ_D : (word5 * word5 * word5) -> FArith_ty
| FEQ_S : (word5 * word5 * word5) -> FArith_ty
| FLE_D : (word5 * word5 * word5) -> FArith_ty
| FLE_S : (word5 * word5 * word5) -> FArith_ty
| FLT_D : (word5 * word5 * word5) -> FArith_ty
| FLT_S : (word5 * word5 * word5) -> FArith_ty
| FMADD_D : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FMADD_S : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FMAX_D : (word5 * word5 * word5) -> FArith_ty
| FMAX_S : (word5 * word5 * word5) -> FArith_ty
| FMIN_D : (word5 * word5 * word5) -> FArith_ty
| FMIN_S : (word5 * word5 * word5) -> FArith_ty
| FMSUB_D : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FMSUB_S : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FMUL_D : (word5 * word5 * word5 * word3) -> FArith_ty
| FMUL_S : (word5 * word5 * word5 * word3) -> FArith_ty
| FNMADD_D : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FNMADD_S : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FNMSUB_D : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FNMSUB_S : (word5 * word5 * word5 * word5 * word3) -> FArith_ty
| FSQRT_D : (word5 * word5 * word3) -> FArith_ty
| FSQRT_S : (word5 * word5 * word3) -> FArith_ty
| FSUB_D : (word5 * word5 * word5 * word3) -> FArith_ty
| FSUB_S : (word5 * word5 * word5 * word3) -> FArith_ty
.
#[global] Instance FArith_ty_inhabited : Inhabited FArith_ty := FADD_D (inhabitant _).

(** HOL datatype [FPStore] (L3 [Construct]). Its Rocq name is [FPStore_ty]: HOL also has a constructor [FPStore] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive FPStore_ty : Type :=
| FSD : (word5 * word5 * word12) -> FPStore_ty
| FSW : (word5 * word5 * word12) -> FPStore_ty
.
#[global] Instance FPStore_ty_inhabited : Inhabited FPStore_ty := FSD (inhabitant _).

(** HOL datatype [FPLoad] (L3 [Construct]). Its Rocq name is [FPLoad_ty]: HOL also has a constructor [FPLoad] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive FPLoad_ty : Type :=
| FLD : (word5 * word5 * word12) -> FPLoad_ty
| FLW : (word5 * word5 * word12) -> FPLoad_ty
.
#[global] Instance FPLoad_ty_inhabited : Inhabited FPLoad_ty := FLD (inhabitant _).

(** HOL datatype [AMO] (L3 [Construct]). Its Rocq name is [AMO_ty]: HOL also has a constructor [AMO] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive AMO_ty : Type :=
| AMOADD_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOADD_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOAND_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOAND_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMAXU_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMAXU_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMAX_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMAX_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMINU_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMINU_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMIN_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOMIN_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOOR_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOOR_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOSWAP_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOSWAP_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOXOR_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| AMOXOR_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| LR_D : (word1 * word1 * word5 * word5) -> AMO_ty
| LR_W : (word1 * word1 * word5 * word5) -> AMO_ty
| SC_D : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
| SC_W : (word1 * word1 * word5 * word5 * word5) -> AMO_ty
.
#[global] Instance AMO_ty_inhabited : Inhabited AMO_ty := AMOADD_D (inhabitant _).

(** HOL datatype [Store] (L3 [Construct]). Its Rocq name is [Store_ty]: HOL also has a constructor [Store] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive Store_ty : Type :=
| SB : (word5 * word5 * word12) -> Store_ty
| SD : (word5 * word5 * word12) -> Store_ty
| SH : (word5 * word5 * word12) -> Store_ty
| SW : (word5 * word5 * word12) -> Store_ty
.
#[global] Instance Store_ty_inhabited : Inhabited Store_ty := SB (inhabitant _).

(** HOL datatype [Load] (L3 [Construct]). Its Rocq name is [Load_ty]: HOL also has a constructor [Load] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive Load_ty : Type :=
| LB : (word5 * word5 * word12) -> Load_ty
| LBU : (word5 * word5 * word12) -> Load_ty
| LD : (word5 * word5 * word12) -> Load_ty
| LH : (word5 * word5 * word12) -> Load_ty
| LHU : (word5 * word5 * word12) -> Load_ty
| LW : (word5 * word5 * word12) -> Load_ty
| LWU : (word5 * word5 * word12) -> Load_ty
.
#[global] Instance Load_ty_inhabited : Inhabited Load_ty := LB (inhabitant _).

(** HOL datatype [Branch] (L3 [Construct]). Its Rocq name is [Branch_ty]: HOL also has a constructor [Branch] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive Branch_ty : Type :=
| BEQ : (word5 * word5 * word12) -> Branch_ty
| BGE : (word5 * word5 * word12) -> Branch_ty
| BGEU : (word5 * word5 * word12) -> Branch_ty
| BLT : (word5 * word5 * word12) -> Branch_ty
| BLTU : (word5 * word5 * word12) -> Branch_ty
| BNE : (word5 * word5 * word12) -> Branch_ty
| JAL : (word5 * word20) -> Branch_ty
| JALR : (word5 * word5 * word12) -> Branch_ty
.
#[global] Instance Branch_ty_inhabited : Inhabited Branch_ty := BEQ (inhabitant _).

(** HOL datatype [MulDiv] (L3 [Construct]). Its Rocq name is [MulDiv_ty]: HOL also has a constructor [MulDiv] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive MulDiv_ty : Type :=
| DIV : (word5 * word5 * word5) -> MulDiv_ty
| DIVU : (word5 * word5 * word5) -> MulDiv_ty
| DIVUW : (word5 * word5 * word5) -> MulDiv_ty
| DIVW : (word5 * word5 * word5) -> MulDiv_ty
| MUL : (word5 * word5 * word5) -> MulDiv_ty
| MULH : (word5 * word5 * word5) -> MulDiv_ty
| MULHSU : (word5 * word5 * word5) -> MulDiv_ty
| MULHU : (word5 * word5 * word5) -> MulDiv_ty
| MULW : (word5 * word5 * word5) -> MulDiv_ty
| REM : (word5 * word5 * word5) -> MulDiv_ty
| REMU : (word5 * word5 * word5) -> MulDiv_ty
| REMUW : (word5 * word5 * word5) -> MulDiv_ty
| REMW : (word5 * word5 * word5) -> MulDiv_ty
.
#[global] Instance MulDiv_ty_inhabited : Inhabited MulDiv_ty := DIV (inhabitant _).

(** HOL datatype [Shift] (L3 [Construct]). Its Rocq name is [Shift_ty]: HOL also has a constructor [Shift] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive Shift_ty : Type :=
| SLL : (word5 * word5 * word5) -> Shift_ty
| SLLI : (word5 * word5 * word6) -> Shift_ty
| SLLIW : (word5 * word5 * word5) -> Shift_ty
| SLLW : (word5 * word5 * word5) -> Shift_ty
| SRA : (word5 * word5 * word5) -> Shift_ty
| SRAI : (word5 * word5 * word6) -> Shift_ty
| SRAIW : (word5 * word5 * word5) -> Shift_ty
| SRAW : (word5 * word5 * word5) -> Shift_ty
| SRL : (word5 * word5 * word5) -> Shift_ty
| SRLI : (word5 * word5 * word6) -> Shift_ty
| SRLIW : (word5 * word5 * word5) -> Shift_ty
| SRLW : (word5 * word5 * word5) -> Shift_ty
.
#[global] Instance Shift_ty_inhabited : Inhabited Shift_ty := SLL (inhabitant _).

(** HOL datatype [ArithR] (L3 [Construct]). Its Rocq name is [ArithR_ty]: HOL also has a constructor [ArithR] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive ArithR_ty : Type :=
| ADD : (word5 * word5 * word5) -> ArithR_ty
| ADDW : (word5 * word5 * word5) -> ArithR_ty
| AND : (word5 * word5 * word5) -> ArithR_ty
| OR : (word5 * word5 * word5) -> ArithR_ty
| SLT : (word5 * word5 * word5) -> ArithR_ty
| SLTU : (word5 * word5 * word5) -> ArithR_ty
| SUB : (word5 * word5 * word5) -> ArithR_ty
| SUBW : (word5 * word5 * word5) -> ArithR_ty
| XOR : (word5 * word5 * word5) -> ArithR_ty
.
#[global] Instance ArithR_ty_inhabited : Inhabited ArithR_ty := ADD (inhabitant _).

(** HOL datatype [ArithI] (L3 [Construct]). Its Rocq name is [ArithI_ty]: HOL also has a constructor [ArithI] (of [instruction]), and Rocq types and constructors share a namespace. *)
Inductive ArithI_ty : Type :=
| ADDI : (word5 * word5 * word12) -> ArithI_ty
| ADDIW : (word5 * word5 * word12) -> ArithI_ty
| ANDI : (word5 * word5 * word12) -> ArithI_ty
| AUIPC : (word5 * word20) -> ArithI_ty
| LUI : (word5 * word20) -> ArithI_ty
| ORI : (word5 * word5 * word12) -> ArithI_ty
| SLTI : (word5 * word5 * word12) -> ArithI_ty
| SLTIU : (word5 * word5 * word12) -> ArithI_ty
| XORI : (word5 * word5 * word12) -> ArithI_ty
.
#[global] Instance ArithI_ty_inhabited : Inhabited ArithI_ty := ADDI (inhabitant _).

(** HOL datatype [instruction] (L3 [Construct]). *)
Inductive instruction : Type :=
| AMO : AMO_ty -> instruction
| ArithI : ArithI_ty -> instruction
| ArithR : ArithR_ty -> instruction
| Branch : Branch_ty -> instruction
| FArith : FArith_ty -> instruction
| FConv : FConv_ty -> instruction
| FENCE : (word5 * word5 * word4 * word4) -> instruction
| FENCE_I : (word5 * word5 * word12) -> instruction
| FPLoad : FPLoad_ty -> instruction
| FPStore : FPStore_ty -> instruction
| Internal : Internal_ty -> instruction
| Load : Load_ty -> instruction
| MulDiv : MulDiv_ty -> instruction
| Shift : Shift_ty -> instruction
| Store : Store_ty -> instruction
| System : System_ty -> instruction
| UnknownInstruction : instruction
.
#[global] Instance instruction_inhabited : Inhabited instruction := AMO (inhabitant _).

(** HOL datatype [FetchResult] (L3 [Construct]). *)
Inductive FetchResult : Type :=
| F_Error : instruction -> FetchResult
| F_Result : rawInstType -> FetchResult
.
#[global] Instance FetchResult_inhabited : Inhabited FetchResult := F_Error (inhabitant _).

(** HOL datatype [rvc] (L3 [Construct]). *)
Inductive rvc : Type :=
| Comp : word16 -> rvc
| Full : word32 -> rvc
.
#[global] Instance rvc_inhabited : Inhabited rvc := Comp (inhabitant _).

(** HOL datatype [exception] (L3 [Construct]). *)
Inductive exception : Type :=
| INTERNAL_ERROR : string -> exception
| NoException : exception
| UNDEFINED : string -> exception
.
#[global] Instance exception_inhabited : Inhabited exception := INTERNAL_ERROR (inhabitant _).

(** HOL record type [riscv_state] (L3 [Record]); fields are named after HOL's
    accessor constants [riscv_state_<field>]. *)
Record riscv_state : Type := {
  riscv_state_MEM8 : word64 -> word8;
  riscv_state_c_ExitCode : word8 -> word64;
  riscv_state_c_HCSR : word8 -> HypervisorCSR;
  riscv_state_c_MCSR : word8 -> MachineCSR;
  riscv_state_c_NextFetch : word8 -> option TransferControl;
  riscv_state_c_PC : word8 -> word64;
  riscv_state_c_ReserveLoad : word8 -> option word64;
  riscv_state_c_SCSR : word8 -> SupervisorCSR;
  riscv_state_c_Skip : word8 -> word64;
  riscv_state_c_UCSR : word8 -> UserCSR;
  riscv_state_c_cycles : word8 -> word64;
  riscv_state_c_fpr : word8 -> word5 -> word64;
  riscv_state_c_gpr : word8 -> word5 -> word64;
  riscv_state_c_instret : word8 -> word64;
  riscv_state_c_tlb : word8 -> word4 -> option TLBEntry;
  riscv_state_c_update : word8 -> StateDelta;
  riscv_state_clock : word64;
  riscv_state_done : bool;
  riscv_state_exception : exception;
  riscv_state_log : list (N * string);
  riscv_state_procID : word8;
  riscv_state_totalCore : N
}.
#[global] Instance riscv_state_inhabited : Inhabited riscv_state :=
  {| riscv_state_MEM8 := inhabitant _;
     riscv_state_c_ExitCode := inhabitant _;
     riscv_state_c_HCSR := inhabitant _;
     riscv_state_c_MCSR := inhabitant _;
     riscv_state_c_NextFetch := inhabitant _;
     riscv_state_c_PC := inhabitant _;
     riscv_state_c_ReserveLoad := inhabitant _;
     riscv_state_c_SCSR := inhabitant _;
     riscv_state_c_Skip := inhabitant _;
     riscv_state_c_UCSR := inhabitant _;
     riscv_state_c_cycles := inhabitant _;
     riscv_state_c_fpr := inhabitant _;
     riscv_state_c_gpr := inhabitant _;
     riscv_state_c_instret := inhabitant _;
     riscv_state_c_tlb := inhabitant _;
     riscv_state_c_update := inhabitant _;
     riscv_state_clock := inhabitant _;
     riscv_state_done := inhabitant _;
     riscv_state_exception := inhabitant _;
     riscv_state_log := inhabitant _;
     riscv_state_procID := inhabitant _;
     riscv_state_totalCore := inhabitant _ |}.

(** ** Instruction encoding *)

Local Open Scope word_scope.

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "Rtype_def" *)
Definition Rtype '((o, f3, rd, rs1, rs2, f7) : word7 * word3 * word5 * word5 * word5 * word7) : word32 :=
  f7 @@ (rs2 @@ (rs1 @@ (f3 @@ (rd @@ o : word12) : word 15) : word20) : word 25).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "R4type_def" *)
Definition R4type '((o, f3, rd, rs1, rs2, rs3, f2) : word7 * word3 * word5 * word5 * word5 * word5 * word2) : word32 :=
  rs3 @@ (f2 @@ (rs2 @@ (rs1 @@ (f3 @@ (rd @@ o : word12) : word 15) : word20) : word 25) : word 27).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "Itype_def" *)
Definition Itype '((o, f3, rd, rs1, imm) : word7 * word3 * word5 * word5 * word12) : word32 :=
  imm @@ (rs1 @@ (f3 @@ (rd @@ o : word12) : word 15) : word20).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "Stype_def" *)
Definition Stype '((o, f3, rs1, rs2, imm) : word7 * word3 * word5 * word5 * word12) : word32 :=
  ((11 >< 5) imm : word7) @@ (rs2 @@ (rs1 @@ (f3 @@ (((4 >< 0) imm : word5) @@ o : word12) : word 15) : word20) : word 25).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "SBtype_def" *)
Definition SBtype '((o, f3, rs1, rs2, imm) : word7 * word3 * word5 * word5 * word12) : word32 :=
  (if word_bit 11 imm then n2w 1 else n2w 0 : word1) @@ (((9 >< 4) imm : word6) @@ (rs2 @@ (rs1 @@ (f3 @@ (((3 >< 0) imm : word4) @@ ((if word_bit 10 imm then n2w 1 else n2w 0 : word1) @@ o : word8) : word12) : word 15) : word20) : word 25) : word 31).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "Utype_def" *)
Definition Utype '((o, rd, imm) : word7 * word5 * word20) : word32 :=
  imm @@ (rd @@ o : word12).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "UJtype_def" *)
Definition UJtype '((o, rd, imm) : word7 * word5 * word20) : word32 :=
  (if word_bit 19 imm then n2w 1 else n2w 0 : word1) @@ (((9 >< 0) imm : word 10) @@ ((if word_bit 10 imm then n2w 1 else n2w 0 : word1) @@ (((18 >< 11) imm : word8) @@ (rd @@ o : word12) : word20) : word21) : word 31).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "opc_def" *)
Definition opc (code : word8) : word7 :=
  ((4 >< 0) code : word5) @@ (n2w 3 : word2).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "amofunc_def" *)
Definition amofunc '((code, aq, rl) : word5 * word1 * word1) : word7 :=
  code @@ (aq @@ rl : word2).

(*! HOL "HOL/examples/l3-machine-code/riscv/model/riscvScript.sml" "Encode_def" *)
Definition Encode (i : instruction) : word32 :=
  match i with
  | Branch (BEQ (rs1, rs2, imm)) =>
      SBtype (opc (n2w 24), n2w 0, rs1, rs2, imm)
  | Branch (BNE (rs1, rs2, imm)) =>
      SBtype (opc (n2w 24), n2w 1, rs1, rs2, imm)
  | Branch (BLT (rs1, rs2, imm)) =>
      SBtype (opc (n2w 24), n2w 4, rs1, rs2, imm)
  | Branch (BGE (rs1, rs2, imm)) =>
      SBtype (opc (n2w 24), n2w 5, rs1, rs2, imm)
  | Branch (BLTU (rs1, rs2, imm)) =>
      SBtype (opc (n2w 24), n2w 6, rs1, rs2, imm)
  | Branch (BGEU (rs1, rs2, imm)) =>
      SBtype (opc (n2w 24), n2w 7, rs1, rs2, imm)
  | Branch (JALR (rd, rs1, imm)) =>
      Itype (opc (n2w 25), n2w 0, rd, rs1, imm)
  | Branch (JAL (rd, imm)) =>
      UJtype (opc (n2w 27), rd, imm)
  | ArithI (LUI (rd, imm)) =>
      Utype (opc (n2w 13), rd, imm)
  | ArithI (AUIPC (rd, imm)) =>
      Utype (opc (n2w 5), rd, imm)
  | ArithI (ADDI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 0, rd, rs1, imm)
  | Shift (SLLI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 1, rd, rs1, (n2w 0 : word6) @@ imm)
  | ArithI (SLTI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 2, rd, rs1, imm)
  | ArithI (SLTIU (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 3, rd, rs1, imm)
  | ArithI (XORI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 4, rd, rs1, imm)
  | Shift (SRLI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 5, rd, rs1, (n2w 0 : word6) @@ imm)
  | Shift (SRAI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 5, rd, rs1, (n2w 16 : word6) @@ imm)
  | ArithI (ORI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 6, rd, rs1, imm)
  | ArithI (ANDI (rd, rs1, imm)) =>
      Itype (opc (n2w 4), n2w 7, rd, rs1, imm)
  | ArithR (ADD (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 0, rd, rs1, rs2, n2w 0)
  | ArithR (SUB (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 0, rd, rs1, rs2, n2w 32)
  | Shift (SLL (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 1, rd, rs1, rs2, n2w 0)
  | ArithR (SLT (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 2, rd, rs1, rs2, n2w 0)
  | ArithR (SLTU (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 3, rd, rs1, rs2, n2w 0)
  | ArithR (XOR (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 4, rd, rs1, rs2, n2w 0)
  | Shift (SRL (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 5, rd, rs1, rs2, n2w 0)
  | Shift (SRA (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 5, rd, rs1, rs2, n2w 32)
  | ArithR (OR (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 6, rd, rs1, rs2, n2w 0)
  | ArithR (AND (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 7, rd, rs1, rs2, n2w 0)
  | ArithI (ADDIW (rd, rs1, imm)) =>
      Itype (opc (n2w 6), n2w 0, rd, rs1, imm)
  | Shift (SLLIW (rd, rs1, imm)) =>
      Itype (opc (n2w 6), n2w 1, rd, rs1, (n2w 0 : word7) @@ imm)
  | Shift (SRLIW (rd, rs1, imm)) =>
      Itype (opc (n2w 6), n2w 5, rd, rs1, (n2w 0 : word7) @@ imm)
  | Shift (SRAIW (rd, rs1, imm)) =>
      Itype (opc (n2w 6), n2w 5, rd, rs1, (n2w 32 : word7) @@ imm)
  | ArithR (ADDW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 0, rd, rs1, rs2, n2w 0)
  | ArithR (SUBW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 0, rd, rs1, rs2, n2w 32)
  | Shift (SLLW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 1, rd, rs1, rs2, n2w 0)
  | Shift (SRLW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 5, rd, rs1, rs2, n2w 0)
  | Shift (SRAW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 5, rd, rs1, rs2, n2w 32)
  | MulDiv (MUL (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 0, rd, rs1, rs2, n2w 1)
  | MulDiv (MULH (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 1, rd, rs1, rs2, n2w 1)
  | MulDiv (MULHSU (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 2, rd, rs1, rs2, n2w 1)
  | MulDiv (MULHU (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 3, rd, rs1, rs2, n2w 1)
  | MulDiv (DIV (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 4, rd, rs1, rs2, n2w 1)
  | MulDiv (DIVU (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 5, rd, rs1, rs2, n2w 1)
  | MulDiv (REM (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 6, rd, rs1, rs2, n2w 1)
  | MulDiv (REMU (rd, rs1, rs2)) =>
      Rtype (opc (n2w 12), n2w 7, rd, rs1, rs2, n2w 1)
  | MulDiv (MULW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 0, rd, rs1, rs2, n2w 1)
  | MulDiv (DIVW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 4, rd, rs1, rs2, n2w 1)
  | MulDiv (DIVUW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 5, rd, rs1, rs2, n2w 1)
  | MulDiv (REMW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 6, rd, rs1, rs2, n2w 1)
  | MulDiv (REMUW (rd, rs1, rs2)) =>
      Rtype (opc (n2w 14), n2w 7, rd, rs1, rs2, n2w 1)
  | Load (LB (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 0, rd, rs1, imm)
  | Load (LH (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 1, rd, rs1, imm)
  | Load (LW (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 2, rd, rs1, imm)
  | Load (LD (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 3, rd, rs1, imm)
  | Load (LBU (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 4, rd, rs1, imm)
  | Load (LHU (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 5, rd, rs1, imm)
  | Load (LWU (rd, rs1, imm)) =>
      Itype (opc (n2w 0), n2w 6, rd, rs1, imm)
  | Store (SB (rs1, rs2, imm)) =>
      Stype (opc (n2w 8), n2w 0, rs1, rs2, imm)
  | Store (SH (rs1, rs2, imm)) =>
      Stype (opc (n2w 8), n2w 1, rs1, rs2, imm)
  | Store (SW (rs1, rs2, imm)) =>
      Stype (opc (n2w 8), n2w 2, rs1, rs2, imm)
  | Store (SD (rs1, rs2, imm)) =>
      Stype (opc (n2w 8), n2w 3, rs1, rs2, imm)
  | FENCE (rd, rs1, pred, succ) =>
      Itype (opc (n2w 3), n2w 0, rd, rs1, (n2w 0 : word4) @@ (pred @@ succ : word8))
  | FENCE_I (rd, rs1, imm) =>
      Itype (opc (n2w 3), n2w 1, rd, rs1, imm)
  | FArith (FADD_S (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 0)
  | FArith (FSUB_S (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 4)
  | FArith (FMUL_S (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 8)
  | FArith (FDIV_S (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 12)
  | FArith (FSQRT_S (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 44)
  | FArith (FMIN_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs1, rs2, n2w 20)
  | FArith (FMAX_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs1, rs2, n2w 20)
  | FArith (FEQ_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 2, rd, rs1, rs2, n2w 80)
  | FArith (FLT_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs1, rs2, n2w 80)
  | FArith (FLE_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs1, rs2, n2w 80)
  | FArith (FADD_D (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 1)
  | FArith (FSUB_D (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 5)
  | FArith (FMUL_D (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 9)
  | FArith (FDIV_D (rd, rs1, rs2, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs1, rs2, n2w 13)
  | FArith (FSQRT_D (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 45)
  | FArith (FMIN_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs1, rs2, n2w 21)
  | FArith (FMAX_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs1, rs2, n2w 21)
  | FArith (FEQ_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 2, rd, rs1, rs2, n2w 81)
  | FArith (FLT_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs1, rs2, n2w 81)
  | FArith (FLE_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs1, rs2, n2w 81)
  | FPLoad (FLW (rd, rs1, imm)) =>
      Itype (opc (n2w 1), n2w 2, rd, rs1, imm)
  | FPLoad (FLD (rd, rs1, imm)) =>
      Itype (opc (n2w 1), n2w 3, rd, rs1, imm)
  | FPStore (FSW (rs1, rs2, imm)) =>
      Stype (opc (n2w 9), n2w 2, rs1, rs2, imm)
  | FPStore (FSD (rs1, rs2, imm)) =>
      Stype (opc (n2w 9), n2w 3, rs1, rs2, imm)
  | FArith (FMADD_S (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 16), frm, rd, rs1, rs2, rs3, n2w 0)
  | FArith (FMSUB_S (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 17), frm, rd, rs1, rs2, rs3, n2w 0)
  | FArith (FNMSUB_S (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 18), frm, rd, rs1, rs2, rs3, n2w 0)
  | FArith (FNMADD_S (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 19), frm, rd, rs1, rs2, rs3, n2w 0)
  | FArith (FMADD_D (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 16), frm, rd, rs1, rs2, rs3, n2w 1)
  | FArith (FMSUB_D (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 17), frm, rd, rs1, rs2, rs3, n2w 1)
  | FArith (FNMSUB_D (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 18), frm, rd, rs1, rs2, rs3, n2w 1)
  | FArith (FNMADD_D (rd, rs1, rs2, rs3, frm)) =>
      R4type (opc (n2w 19), frm, rd, rs1, rs2, rs3, n2w 1)
  | FConv (FSGNJ_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs1, rs2, n2w 16)
  | FConv (FSGNJN_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs1, rs2, n2w 16)
  | FConv (FSGNJX_S (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 2, rd, rs1, rs2, n2w 16)
  | FConv (FCVT_W_S (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 96)
  | FConv (FCVT_WU_S (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 1, n2w 96)
  | FConv (FMV_X_S (rd, rs)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs, n2w 0, n2w 112)
  | FConv (FCLASS_S (rd, rs)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs, n2w 0, n2w 112)
  | FConv (FCVT_S_W (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 104)
  | FConv (FCVT_S_WU (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 1, n2w 104)
  | FConv (FMV_S_X (rd, rs)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs, n2w 0, n2w 120)
  | FConv (FSGNJ_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs1, rs2, n2w 17)
  | FConv (FSGNJN_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs1, rs2, n2w 17)
  | FConv (FSGNJX_D (rd, rs1, rs2)) =>
      Rtype (opc (n2w 20), n2w 2, rd, rs1, rs2, n2w 17)
  | FConv (FCVT_W_D (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 97)
  | FConv (FCVT_WU_D (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 1, n2w 97)
  | FConv (FCLASS_D (rd, rs)) =>
      Rtype (opc (n2w 20), n2w 1, rd, rs, n2w 0, n2w 113)
  | FConv (FCVT_D_W (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 105)
  | FConv (FCVT_D_WU (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 1, n2w 105)
  | FConv (FCVT_S_D (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 1, n2w 32)
  | FConv (FCVT_D_S (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 0, n2w 33)
  | FConv (FCVT_L_S (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 2, n2w 96)
  | FConv (FCVT_LU_S (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 3, n2w 96)
  | FConv (FCVT_S_L (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 2, n2w 104)
  | FConv (FCVT_S_LU (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 3, n2w 104)
  | FConv (FCVT_L_D (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 2, n2w 97)
  | FConv (FCVT_LU_D (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 3, n2w 97)
  | FConv (FMV_X_D (rd, rs)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs, n2w 0, n2w 113)
  | FConv (FCVT_D_L (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 2, n2w 105)
  | FConv (FCVT_D_LU (rd, rs, frm)) =>
      Rtype (opc (n2w 20), frm, rd, rs, n2w 3, n2w 105)
  | FConv (FMV_D_X (rd, rs)) =>
      Rtype (opc (n2w 20), n2w 0, rd, rs, n2w 0, n2w 121)
  | AMO (LR_W (aq, rl, rd, rs1)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, n2w 0, amofunc (n2w 2, aq, rl))
  | AMO (LR_D (aq, rl, rd, rs1)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, n2w 0, amofunc (n2w 2, aq, rl))
  | AMO (SC_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 3, aq, rl))
  | AMO (SC_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 2, aq, rl))
  | AMO (AMOSWAP_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 1, aq, rl))
  | AMO (AMOADD_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 0, aq, rl))
  | AMO (AMOXOR_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 4, aq, rl))
  | AMO (AMOAND_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 12, aq, rl))
  | AMO (AMOOR_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 8, aq, rl))
  | AMO (AMOMIN_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 16, aq, rl))
  | AMO (AMOMAX_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 20, aq, rl))
  | AMO (AMOMINU_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 24, aq, rl))
  | AMO (AMOMAXU_W (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 2, rd, rs1, rs2, amofunc (n2w 28, aq, rl))
  | AMO (AMOSWAP_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 1, aq, rl))
  | AMO (AMOADD_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 0, aq, rl))
  | AMO (AMOXOR_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 4, aq, rl))
  | AMO (AMOAND_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 12, aq, rl))
  | AMO (AMOOR_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 8, aq, rl))
  | AMO (AMOMIN_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 16, aq, rl))
  | AMO (AMOMAX_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 20, aq, rl))
  | AMO (AMOMINU_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 24, aq, rl))
  | AMO (AMOMAXU_D (aq, rl, rd, rs1, rs2)) =>
      Rtype (opc (n2w 11), n2w 3, rd, rs1, rs2, amofunc (n2w 28, aq, rl))
  | System ECALL =>
      Itype (opc (n2w 28), n2w 0, n2w 0, n2w 0, n2w 0)
  | System EBREAK =>
      Itype (opc (n2w 28), n2w 0, n2w 0, n2w 0, n2w 1)
  | System ERET =>
      Itype (opc (n2w 28), n2w 0, n2w 0, n2w 0, n2w 256)
  | System MRTS =>
      Itype (opc (n2w 28), n2w 0, n2w 0, n2w 0, n2w 773)
  | System WFI =>
      Itype (opc (n2w 28), n2w 0, n2w 0, n2w 0, n2w 258)
  | System (SFENCE_VM rs1) =>
      Itype (opc (n2w 28), n2w 0, n2w 0, rs1, n2w 257)
  | System (CSRRW (rd, rs1, csr)) =>
      Itype (opc (n2w 28), n2w 1, rd, rs1, csr)
  | System (CSRRS (rd, rs1, csr)) =>
      Itype (opc (n2w 28), n2w 2, rd, rs1, csr)
  | System (CSRRC (rd, rs1, csr)) =>
      Itype (opc (n2w 28), n2w 3, rd, rs1, csr)
  | System (CSRRWI (rd, imm, csr)) =>
      Itype (opc (n2w 28), n2w 5, rd, imm, csr)
  | System (CSRRSI (rd, imm, csr)) =>
      Itype (opc (n2w 28), n2w 6, rd, imm, csr)
  | System (CSRRCI (rd, imm, csr)) =>
      Itype (opc (n2w 28), n2w 7, rd, imm, csr)
  | UnknownInstruction =>
      n2w 0
  | Internal (FETCH_MISALIGNED _) =>
      n2w 0
  | Internal (FETCH_FAULT _) =>
      n2w 0
  end.
