(** * CakeML [asmProps]: properties of the asm language

    Port of [cakeml/compiler/encoders/asm/asmPropsScript.sml].

    [all_pcs] is defined as the set that HOL's [all_pcs_thm] gives, and
    HOL's recursive equations are the theorem [all_pcs_def]; [asserts] and
    [asserts2] are defined by primitive recursion ([num_rec]) and HOL's
    equations are [asserts_def], [asserts2_def].

    Not ported: [asserts_eval] and [asserts2_eval] (lists of 20 unfolded
    instances of the equations, generated by ML), the [SUC]-form copy
    [all_pcs] of [all_pcs_def] (its name is also the constant's).

    HOL's [('a,'b,'c) target] is [target a B C] (width index [a], machine
    state [B], projection type [C]); its fields carry HOL's names.  As in
    [asmSem], the short names [asm], [inst] denote [asmSem]'s functions;
    the types are [asm.asm], [asm.inst]. *)

From Galette Require Import Base.
From Galette.HOL.src.num.theories Require Import arithmetic.
From Galette.HOL.src.n_bit Require Import words.
From Galette.HOL.src.list.src Require Import list.
From Galette.HOL.src.pred_set.src Require Import pred_set.
From Galette.HOL.src.list.src Require Import rich_list.
From Galette.HOL.src.relation Require Import relation.
From Galette.HOL.src.combin Require Import combin.
From Galette.cakeml.misc Require Import misc.
From Galette.cakeml.compiler.encoders.asm Require Import asm asmSem.
Open Scope N_scope.

(** ** Semantics is deterministic *)

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asm_deterministic" *)
Theorem asm_deterministic : forall {a} (c : asm_config a) i (s1 s2 s3 : asm_state a),
  asm_step c s1 i s2 /\ asm_step c s1 i s3 -> s2 = s3.
Proof.
  intros a c i s1 s2 s3 [(_ & _ & _ & _ & H2 & _) (_ & _ & _ & _ & H3 & _)].
  rewrite <- H2, <- H3; reflexivity.
Qed.

(** ** Well-formedness of encoding *)

Section Enc.
Context {a : N}.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "offset_monotonic_def" *)
Definition offset_monotonic (enc : asm.asm a -> list word8) (c : asm_config a)
    (a1 a2 : word a) (i1 i2 : asm.asm a) : Prop :=
  asm_ok i1 c /\ asm_ok i2 c ->
  ((n2w 0 <= a1)%w /\ (n2w 0 <= a2)%w /\ (a1 <= a2)%w -> LENGTH (enc i1) <= LENGTH (enc i2)) /\
  ((a1 < n2w 0)%w /\ (a2 < n2w 0)%w /\ (a2 <= a1)%w -> LENGTH (enc i1) <= LENGTH (enc i2)).

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "enc_ok_def" *)
Definition enc_ok (c : asm_config a) : Prop :=
  (* code alignment and length *)
  (2 ** code_alignment c = LENGTH (encode c (Inst Skip))) /\
  (forall w, (LENGTH (encode c w) MOD 2 ** code_alignment c = 0) /\
             LENGTH (encode c w) <> 0) /\
  (* label instantiation predictably affects length of code *)
  (forall w1 w2, offset_monotonic (encode c) c w1 w2 (Jump w1) (Jump w2)) /\
  (forall cmp r ri w1 w2,
     offset_monotonic (encode c) c w1 w2
       (JumpCmp cmp r ri w1) (JumpCmp cmp r ri w2)) /\
  (forall w1 w2, offset_monotonic (encode c) c w1 w2 (Call w1) (Call w2)) /\
  (forall w1 w2 r, offset_monotonic (encode c) c w1 w2 (Loc r w1) (Loc r w2)).

End Enc.

(** ** Targets *)

(** HOL's record [target], fields in HOL's order. *)
(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "target" *)
Record target (a : N) (B C : Type) : Type := mk_target {
  config : asm_config a;
  next : B -> B;
  get_pc : B -> word a;
  get_reg : B -> N -> word a;
  get_fp_reg : B -> N -> word64;
  get_byte : B -> word a -> word8;
  state_ok : B -> bool;
  proj : (word a -> Prop) -> B -> C
}.
Arguments mk_target {a B C} _ _ _ _ _ _ _ _.
Arguments config {a B C} _.
Arguments next {a B C} _ _.
Arguments get_pc {a B C} _ _.
Arguments get_reg {a B C} _ _ _.
Arguments get_fp_reg {a B C} _ _ _.
Arguments get_byte {a B C} _ _ _.
Arguments state_ok {a B C} _ _.
Arguments proj {a B C} _ _ _.

Section Targets.
Context {a : N} {B C : Type}.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "target_state_rel_def" *)
Definition target_state_rel (t : target a B C) (s : asm_state a) (ms : B) : Prop :=
  state_ok t ms /\ (get_pc t ms = s.(pc)) /\
  (forall ad, ad IN s.(mem_domain) -> get_byte t ms ad = s.(mem) ad) /\
  (forall i, i < reg_count (config t) /\ ~ MEM i (avoid_regs (config t)) ->
     get_reg t ms i = s.(regs) i) /\
  (forall i, i < fp_reg_count (config t) -> get_fp_reg t ms i = s.(fp_regs) i).

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "target_ok_def" *)
Definition target_ok (t : target a B C) : Prop :=
  enc_ok (config t) /\
  forall ms1 ms2 (s : asm_state a),
    proj t s.(mem_domain) ms1 = proj t s.(mem_domain) ms2 ->
    (target_state_rel t s ms1 <-> target_state_rel t s ms2) /\
    (state_ok t ms1 = state_ok t ms2) /\
    (get_pc t ms1 = get_pc t ms2) /\
    (forall ad, ad IN s.(mem_domain) -> get_byte t ms1 ad = get_byte t ms2 ad).

End Targets.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "interference_ok_def" *)
Definition interference_ok {B C : Type} (env : N -> B -> B) (proj : B -> C) : Prop :=
  forall (i : N) ms, proj (env i ms) = proj ms.

(** ** Program counters of an instruction *)

Section Pcs.
Context {a : N}.

(** [all_pcs n ad k]: the [2 ** k]-aligned offsets from [ad] below [n]. *)
Definition all_pcs (n : N) (ad : word a) (k : N) : word a -> Prop :=
  fun x => exists i, x = (ad + n2w (i * 2 ** k))%w /\ i * 2 ** k < n.

Lemma word_add_n2w_add (x : word a) p q :
  (x + n2w (p + q))%w = ((x + n2w p) + n2w q)%w.
Proof.
  apply word_eq_w2n; unfold word_add; rewrite !w2n_n2w.
  transitivity ((w2n x + p + q) MOD dimword a).
  - rewrite N.Div0.add_mod_idemp_r, N.add_assoc; reflexivity.
  - rewrite N.Div0.add_mod_idemp_r, N.Div0.add_mod_idemp_l.
    rewrite (N.add_comm (w2n x + p MOD dimword a) q), N.add_assoc, N.Div0.add_mod_idemp_r.
    f_equal; lia.
Qed.

Lemma word_add_n2w_0 (x : word a) : (x + n2w 0)%w = x.
Proof.
  apply word_eq_w2n; unfold word_add; rewrite !w2n_n2w, N.Div0.mod_0_l, N.add_0_r.
  apply N.mod_small, w2n_lt.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "all_pcs_def" *)
Theorem all_pcs_def : forall n (ad : word a) k,
  all_pcs 0 ad k = EMPTY /\
  all_pcs (SUC n) ad k = ad INSERT all_pcs (SUC n - 2 ** k) (ad + n2w (2 ** k))%w k.
Proof.
  intros n ad k; split.
  - apply functional_extensionality; intros x; apply propositional_extensionality.
    unfold EMPTY, all_pcs; split; [intros (i & _ & H); lia|tauto].
  - apply functional_extensionality; intros x; apply propositional_extensionality.
    unfold pred_set.INSERT, pred_set.IN, all_pcs; split.
    + intros (i & -> & Hi).
      destruct i as [|i] using N.peano_ind.
      * left; rewrite N.mul_0_l; apply word_add_n2w_0.
      * right; exists i; split; [|lia].
        rewrite <- word_add_n2w_add; f_equal; f_equal; lia.
    + intros [->|(i & -> & Hi)].
      * exists 0; rewrite N.mul_0_l, word_add_n2w_0; split; [reflexivity|lia].
      * exists (SUC i); rewrite <- word_add_n2w_add; split; [f_equal; f_equal; lia|lia].
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "all_pcs_thm" *)
Theorem all_pcs_thm : forall n (ad : word a) k,
  all_pcs n ad k = (fun x => exists i, x = (ad + n2w (i * 2 ** k))%w /\ i * 2 ** k < n).
Proof. reflexivity. Qed.

End Pcs.

(** ** Assertions along a run *)

Section Asserts.
Context {B : Type}.

Definition asserts (n : N) (next : N -> B -> B) (ms : B) (P Q : B -> Prop) : Prop :=
  num_rec (fun ms => Q (next 0 ms))
    (fun n r ms => let ms' := next (SUC n) ms in P ms' /\ r ms') n ms.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts_def" *)
Theorem asserts_def : forall n next ms P Q,
  asserts 0 next ms P Q = Q (next 0 ms) /\
  asserts (SUC n) next ms P Q =
    (let ms' := next (SUC n) ms in P ms' /\ asserts n next ms' P Q).
Proof.
  intros; split; [reflexivity|]. unfold asserts; rewrite num_rec_SUC; reflexivity.
Qed.

Definition asserts2 (n : N) (fi : N -> B -> B) (fc : B -> B) (ms : B)
    (P : B -> B -> Prop) : Prop :=
  num_rec (fun _ => True)
    (fun m r ms => P ms (fc ms) /\ r (fi (SUC m) (fc ms))) n ms.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts2_def" *)
Theorem asserts2_def : forall n fi fc ms P,
  asserts2 n fi fc ms P =
  if bool_decide (n = 0) then True else
    P ms (fc ms) /\ asserts2 (n - 1) fi fc (fi n (fc ms)) P.
Proof.
  intros n fi fc ms P; destruct n as [|n] using N.peano_ind; [reflexivity|].
  unfold bool_decide; destruct (decide (N.succ n = 0)) as [H|_]; [lia|].
  unfold asserts2 at 1; rewrite num_rec_SUC.
  replace (N.succ n - 1) with n by lia; reflexivity.
Qed.

End Asserts.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts2_every" *)
Theorem asserts2_every : forall {B} (f g : B -> B) P n ms j,
  asserts2 n (fun k => f) g ms P /\ j < n ->
  P (FUNPOW (fun x => f (g x)) j ms) (g (FUNPOW (fun x => f (g x)) j ms)).
Proof.
  intros B f g P n; induction n as [|n IH] using N.peano_ind; intros ms j [H Hj]; [lia|].
  unfold asserts2 in H; rewrite num_rec_SUC in H; fold (asserts2 n (fun k => f) g (f (g ms)) P) in H.
  destruct H as [H0 H1].
  destruct j as [|j] using N.peano_ind; [exact H0|].
  rewrite !FUNPOW_SUC_r. apply IH; split; [exact H1|lia].
Qed.

(** ** The correctness property to be proved for each backend *)

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "encoder_correct_def" *)
Definition encoder_correct {a : N} {B C : Type} (t : target a B C) : Prop :=
  target_ok t /\
  forall s1 i s2 ms,
    asm_step (config t) s1 i s2 /\ target_state_rel t s1 ms ->
    exists n, forall (env : N -> B -> B),
      interference_ok env (proj t s1.(mem_domain)) ->
      let pcs := all_pcs (LENGTH (encode (config t) i)) s1.(pc) in
      asserts n (fun k s => env (n - k) (next t s)) ms
        (fun ms' => state_ok t ms' /\
           (forall pc0, pc0 IN pcs 0 -> get_byte t ms' pc0 = get_byte t ms pc0) /\
           get_pc t ms' IN pcs (code_alignment (config t)))
        (fun ms' => target_state_rel t s2 ms') /\
      asserts2 (n + 1) (fun k => env (n + 1 - k)) (next t) ms
        (fun ms1 ms2 => forall x, x NOTIN s1.(mem_domain) ->
           get_byte t ms1 x = get_byte t ms2 x).

(** ** Lemmas *)

Section Lemmas.
Context {a : N}.

Lemma bytes_in_memory_IN (m : word a -> word8) d : forall xs pc0 j,
  bytes_in_memory pc0 xs m d -> j < LENGTH xs -> (pc0 + n2w j)%w IN d.
Proof.
  intros xs; induction xs as [|x xs IH]; intros pc0 j H Hj; cbn [LENGTH] in Hj; [lia|].
  destruct H as (_ & Hd & H).
  destruct j as [|j] using N.peano_ind.
  - rewrite word_add_n2w_0; exact Hd.
  - replace (N.succ j) with (1 + j) by lia; rewrite word_add_n2w_add.
    apply IH; [exact H|lia].
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "bytes_in_memory_all_pcs" *)
Theorem bytes_in_memory_all_pcs : forall (m : word a -> word8) d k xs pc0,
  bytes_in_memory pc0 xs m d -> all_pcs (LENGTH xs) pc0 k SUBSET d.
Proof.
  intros m d k xs pc0 H x (i & -> & Hi).
  eapply bytes_in_memory_IN; eauto.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "read_bytearray_IMP_bytes_in_memory" *)
Theorem read_bytearray_IMP_bytes_in_memory :
  forall (p : word a) n (m : word a -> option word8) ba m' md,
  n = LENGTH ba /\
  (forall k, k IN all_words p n -> k IN md /\ m k = Some (m' k)) /\
  read_bytearray p n m = Some ba ->
  bytes_in_memory p ba m' md.
Proof.
  intros p n m ba; revert p n; induction ba as [|b ba IH]; intros p n m' md (-> & Hk & Hr);
    [exact Logic.I|].
  cbn [LENGTH] in *.
  rewrite (proj2 (read_bytearray_def p m (LENGTH ba))) in Hr.
  destruct (m p) as [b'|] eqn:Ep; [|discriminate].
  destruct (read_bytearray (p + n2w 1)%w (LENGTH ba) m) as [bs|] eqn:Eb; [|discriminate].
  injection Hr as <- <-.
  assert (Hp : p IN all_words p (SUC (LENGTH bs))).
  { unfold pred_set.IN; rewrite (proj2 (all_words_def p (LENGTH bs))); left; reflexivity. }
  destruct (Hk p Hp) as [Hmd Hm]; rewrite Ep in Hm; injection Hm as ->.
  cbn [bytes_in_memory]; split; [reflexivity|split; [exact Hmd|]].
  apply (IH (p + n2w 1)%w (LENGTH bs) m' md); split; [reflexivity|split; [|exact Eb]].
  intros k' Hk'; apply Hk; unfold pred_set.IN in *; rewrite (proj2 (all_words_def p (LENGTH bs))).
  right; exact Hk'.
Qed.

End Lemmas.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "sym_target_state_rel" *)
Theorem sym_target_state_rel : forall {a B C} (t : target a B C) s ms,
  target_state_rel t s ms <->
  state_ok t ms /\ (s.(pc) = get_pc t ms) /\
  (forall ad, ad IN s.(mem_domain) -> s.(mem) ad = get_byte t ms ad) /\
  (forall i, i < reg_count (config t) /\ ~ MEM i (avoid_regs (config t)) ->
     s.(regs) i = get_reg t ms i) /\
  (forall i, i < fp_reg_count (config t) -> s.(fp_regs) i = get_fp_reg t ms i).
Proof.
  intros a B C t s ms; unfold target_state_rel; split;
    intros (H1 & H2 & H3 & H4 & H5); repeat split; auto;
    intros; symmetry; auto.
Qed.

Section AssertsLemmas.
Context {B : Type}.

Lemma FOLDR_app {X Y} (f : X -> Y -> Y) e l1 l2 :
  FOLDR f e (l1 ++ l2) = FOLDR f (FOLDR f e l2) l1.
Proof. induction l1 as [|x l1 IH]; cbn; [reflexivity|rewrite IH; reflexivity]. Qed.

Lemma COUNT_LIST_SUC n : COUNT_LIST (SUC n) = COUNT_LIST n ++ [n].
Proof.
  rewrite !COUNT_LIST_GENLIST, (proj2 (GENLIST_thm I n)), SNOC_app; reflexivity.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts_IMP_FOLDR_COUNT_LIST" *)
Theorem asserts_IMP_FOLDR_COUNT_LIST : forall n (next : N -> B -> B) ms P Q,
  asserts n next ms P Q -> Q (FOLDR next (next n ms) (COUNT_LIST n)).
Proof.
  intros n; induction n as [|n IH] using N.peano_ind; intros next ms P Q H.
  - exact H.
  - rewrite (proj2 (asserts_def n next ms P Q)) in H; destruct H as [_ H].
    rewrite COUNT_LIST_SUC, FOLDR_app; cbn [FOLDR].
    exact (IH next _ P Q H).
Qed.

Lemma FOLDR_REVERSE_GENLIST_SUC (f : N -> B -> B) s m j :
  FOLDR f s (REVERSE (GENLIST (fun i => SUC m - i) (SUC j))) =
  FOLDR f (f (SUC m) s) (REVERSE (GENLIST (fun i => m - i) j)).
Proof.
  rewrite GENLIST_CONS_aux, (proj2 (REVERSE_DEF _ _)), FOLDR_app; cbn [FOLDR].
  replace (SUC m - 0) with (SUC m) by lia.
  replace (fun i => SUC m - SUC i) with (fun i => m - i)
    by (apply functional_extensionality; intros; lia).
  reflexivity.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts_IMP_FOLDR_COUNT_LIST_LESS" *)
Theorem asserts_IMP_FOLDR_COUNT_LIST_LESS : forall k n (next : N -> B -> B) ms P Q,
  asserts n next ms P Q /\ k < n ->
  P (FOLDR next ms (REVERSE (GENLIST (fun i => n - i) (SUC k)))).
Proof.
  intros k; induction k as [|k IH] using N.peano_ind; intros n next ms P Q [H Hk];
    (destruct n as [|n] using N.peano_ind; [lia|]);
    rewrite (proj2 (asserts_def n next ms P Q)) in H; destruct H as [HP H];
    rewrite FOLDR_REVERSE_GENLIST_SUC.
  - exact HP.
  - apply (IH n next _ P Q); split; [exact H|lia].
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts_WEAKEN" *)
Theorem asserts_WEAKEN : forall n (next next' : N -> B -> B) s (P P' Q : B -> Prop),
  (forall k, k <= n ->
     next k = next' k /\
     (P (FOLDR next s (REVERSE (GENLIST (fun i => n - i) (SUC k)))) ->
      P' (FOLDR next s (REVERSE (GENLIST (fun i => n - i) (SUC k)))))) ->
  asserts n next s P Q -> asserts n next' s P' Q.
Proof.
  intros n; induction n as [|n IH] using N.peano_ind; intros next next' s P P' Q Hk H.
  - destruct (Hk 0 ltac:(lia)) as [E _]; cbn in *; unfold asserts in *; cbn in *.
    rewrite <- E; exact H.
  - rewrite (proj2 (asserts_def n next s P Q)) in H.
    rewrite (proj2 (asserts_def n next' s P' Q)); cbv zeta in *.
    destruct H as [HP H].
    destruct (Hk (SUC n) ltac:(lia)) as [E _]; rewrite <- E.
    split.
    + destruct (Hk 0 ltac:(lia)) as [_ HP'].
      rewrite FOLDR_REVERSE_GENLIST_SUC in HP'; exact (HP' HP).
    + apply (IH next next' _ P P' Q); [|exact H].
      intros k Hkn; destruct (Hk (SUC k) ltac:(lia)) as [_ HPk]; split;
        [exact (proj1 (Hk k ltac:(lia)))|].
      rewrite !FOLDR_REVERSE_GENLIST_SUC in HPk; exact HPk.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts2_change_interfer" *)
Theorem asserts2_change_interfer : forall n (fi fi2 : N -> B -> B) fc ms P,
  asserts2 n fi fc ms P /\ (forall k, k <= n -> fi k = fi2 k) ->
  asserts2 n fi2 fc ms P.
Proof.
  intros n; induction n as [|n IH] using N.peano_ind; intros fi fi2 fc ms P [H Hk];
    [exact Logic.I|].
  unfold asserts2 in *; rewrite num_rec_SUC in *; destruct H as [HP H].
  split; [exact HP|]. rewrite <- (Hk (SUC n)) by lia.
  apply (IH fi fi2); split; [exact H|intros; apply Hk; lia].
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asserts2_first" *)
Theorem asserts2_first : forall n (fi : N -> B -> B) fc ms P,
  1 <= n /\ asserts2 n fi fc ms P -> P ms (fc ms).
Proof.
  intros n fi fc ms P [Hn H]; destruct n as [|n] using N.peano_ind; [lia|].
  unfold asserts2 in H; rewrite num_rec_SUC in H; exact (proj1 H).
Qed.

End AssertsLemmas.

(** ** Components preserved by the semantics *)

Section Consts.
Context {a : N}.
Implicit Types (s x : asm_state a).

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "upd_pc_simps" *)
Theorem upd_pc_simps : forall (pc0 : word a) s,
  (upd_pc pc0 s).(align) = s.(align) /\
  (upd_pc pc0 s).(mem_domain) = s.(mem_domain) /\
  (upd_pc pc0 s).(failed) = s.(failed) /\
  (upd_pc pc0 s).(be) = s.(be) /\
  (upd_pc pc0 s).(mem) = s.(mem) /\
  (upd_pc pc0 s).(regs) = s.(regs) /\
  (upd_pc pc0 s).(fp_regs) = s.(fp_regs) /\
  (upd_pc pc0 s).(lr) = s.(lr) /\
  (upd_pc pc0 s).(pc) = pc0.
Proof. intros; repeat split. Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asm_failed_ignore_new_pc" *)
Theorem asm_failed_ignore_new_pc : forall (i : asm.asm a) v w s,
  (asm i w s).(failed) = (asm i v s).(failed).
Proof.
  intros i v w s; destruct i; cbn; try reflexivity.
  destruct (word_cmp _ _ _); reflexivity.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asm_mem_ignore_new_pc" *)
Theorem asm_mem_ignore_new_pc : forall (i : asm.asm a) v w s,
  (asm i w s).(mem) = (asm i v s).(mem).
Proof.
  intros i v w s; destruct i; cbn; try reflexivity.
  destruct (word_cmp _ _ _); reflexivity.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "SND_read_mem_word_consts" *)
Theorem SND_read_mem_word_consts : forall n (ad : word a) s,
  (snd (read_mem_word ad n s)).(be) = s.(be) /\
  (snd (read_mem_word ad n s)).(lr) = s.(lr) /\
  (snd (read_mem_word ad n s)).(align) = s.(align) /\
  (snd (read_mem_word ad n s)).(mem_domain) = s.(mem_domain).
Proof.
  intros n; induction n as [|n IH] using N.peano_ind; intros ad s; [repeat split|].
  rewrite (proj2 (read_mem_word_def ad n s)).
  specialize (IH (if s.(be) then (ad - n2w 1)%w else (ad + n2w 1)%w) s).
  destruct (read_mem_word _ n s) as [w s1]; cbn in *; exact IH.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "write_mem_word_consts" *)
Theorem write_mem_word_consts : forall n (ad : word a) w s,
  (write_mem_word ad n w s).(be) = s.(be) /\
  (write_mem_word ad n w s).(lr) = s.(lr) /\
  (write_mem_word ad n w s).(align) = s.(align) /\
  (write_mem_word ad n w s).(mem_domain) = s.(mem_domain).
Proof.
  intros n; induction n as [|n IH] using N.peano_ind; intros ad w s; [repeat split|].
  rewrite (proj2 (write_mem_word_def ad n w s)); cbv zeta.
  exact (IH _ _ s).
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "binop_upd_consts" *)
Theorem binop_upd_consts : forall r b (c d : word a) x,
  (binop_upd r b c d x).(mem_domain) = x.(mem_domain) /\
  (binop_upd r b c d x).(align) = x.(align) /\
  (binop_upd r b c d x).(failed) = x.(failed) /\
  (binop_upd r b c d x).(mem) = x.(mem) /\
  (binop_upd r b c d x).(lr) = x.(lr) /\
  (binop_upd r b c d x).(be) = x.(be).
Proof. intros r b c d x; destruct b; repeat split. Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "arith_upd_consts" *)
Theorem arith_upd_consts : forall (y : arith a) x,
  (arith_upd y x).(mem_domain) = x.(mem_domain) /\
  (arith_upd y x).(align) = x.(align) /\
  (arith_upd y x).(mem) = x.(mem) /\
  (arith_upd y x).(lr) = x.(lr) /\
  (arith_upd y x).(be) = x.(be).
Proof.
  intros y x; destruct y; cbn -[binop_upd]; try (repeat split; fail).
  pose proof (binop_upd_consts n b (read_reg n0 x) (reg_imm r x) x) as H.
  destruct H as (H1 & H2 & _ & H4 & H5 & H6); repeat split; assumption.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "fp_upd_consts" *)
Theorem fp_upd_consts : forall (y : fp) x,
  (fp_upd y x).(mem_domain) = x.(mem_domain) /\
  (fp_upd y x).(align) = x.(align) /\
  (fp_upd y x).(mem) = x.(mem) /\
  (fp_upd y x).(lr) = x.(lr) /\
  (fp_upd y x).(be) = x.(be).
Proof.
  intros y x; destruct y; cbn; try (repeat split; fail);
    repeat (match goal with
            | |- context [match ?e with _ => _ end] => destruct e
            | |- context [if ?e then _ else _] => destruct e
            end; cbn beta iota zeta); repeat split.
Qed.

Lemma mem_load_consts n r (y : asm.addr a) x :
  (mem_load n r y x).(be) = x.(be) /\ (mem_load n r y x).(lr) = x.(lr) /\
  (mem_load n r y x).(align) = x.(align) /\
  (mem_load n r y x).(mem_domain) = x.(mem_domain).
Proof.
  unfold mem_load; cbv zeta.
  pose proof (SND_read_mem_word_consts n
    (if x.(be) then (addr y x + n2w (n - 1))%w else addr y x) x) as H.
  destruct (read_mem_word _ n x) as [w s1]; cbn in *; exact H.
Qed.

Lemma mem_store_consts n r (y : asm.addr a) x :
  (mem_store n r y x).(be) = x.(be) /\ (mem_store n r y x).(lr) = x.(lr) /\
  (mem_store n r y x).(align) = x.(align) /\
  (mem_store n r y x).(mem_domain) = x.(mem_domain).
Proof. unfold mem_store; cbv zeta; apply write_mem_word_consts. Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asm_consts" *)
Theorem asm_consts : forall (i : asm.asm a) w s,
  (asm i w s).(be) = s.(be) /\
  (asm i w s).(lr) = s.(lr) /\
  (asm i w s).(align) = s.(align) /\
  (asm i w s).(mem_domain) = s.(mem_domain).
Proof.
  intros i w s; destruct i as [i| | | | |]; cbn -[inst];
    try (destruct (word_cmp _ _ _)); try (repeat split; fail).
  destruct i as [| |y|m r y|y]; cbn -[arith_upd fp_upd mem_op]; try (repeat split; fail).
  - destruct (arith_upd_consts y s) as (H1 & H2 & _ & H4 & H5); repeat split; assumption.
  - destruct m; cbn -[mem_load mem_store];
      first [apply mem_load_consts|apply mem_store_consts].
  - destruct (fp_upd_consts y s) as (H1 & H2 & _ & H4 & H5); repeat split; assumption.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "RTC_asm_step_consts" *)
Theorem RTC_asm_step_consts : forall (c : asm_config a) s1 s2,
  RTC (fun s1 s2 => exists i, asm_step c s1 i s2) s1 s2 ->
  s2.(mem_domain) = s1.(mem_domain) /\
  s2.(lr) = s1.(lr) /\
  s2.(align) = s1.(align) /\
  s2.(be) = s1.(be).
Proof.
  intros c s1 s2 H; induction H as [x|x y z (i & Hs) _ IH]; [repeat split|].
  destruct Hs as (_ & _ & _ & _ & <- & _).
  destruct (asm_consts i (x.(pc) + n2w (LENGTH (encode c i)))%w x) as (E1 & E2 & E3 & E4).
  destruct IH as (I1 & I2 & I3 & I4).
  repeat split; congruence.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "read_mem_word_IMP_mem_eq" *)
Theorem read_mem_word_IMP_mem_eq : forall (ad : word a) k s w s',
  read_mem_word ad k s = (w, s') -> s'.(mem) = s.(mem).
Proof.
  intros ad k; revert ad; induction k as [|k IH] using N.peano_ind; intros ad s w s' H.
  - injection H as _ <-; reflexivity.
  - rewrite (proj2 (read_mem_word_def ad k s)) in H.
    destruct (read_mem_word _ k s) as [w1 s1] eqn:E.
    injection H as _ <-; cbn; exact (IH _ s w1 s1 E).
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "write_mem_word_mem_domain" *)
Theorem write_mem_word_mem_domain : forall k (b w : word a) s,
  (write_mem_word b k w s).(mem_domain) = s.(mem_domain).
Proof. intros k b w s; apply (write_mem_word_consts k b w s). Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "write_mem_word_mem_eq" *)
Theorem write_mem_word_mem_eq : forall k (b w : word a) s (x : word a),
  ~ (write_mem_word b k w s).(failed) /\ x NOTIN s.(mem_domain) ->
  (write_mem_word b k w s).(mem) x = s.(mem) x.
Proof.
  intros k; induction k as [|k IH] using N.peano_ind; intros b w s x [Hf Hx]; [reflexivity|].
  rewrite (proj2 (write_mem_word_def b k w s)) in *; cbv zeta in *.
  set (s1 := write_mem_word _ k _ s) in *.
  unfold assert, upd_mem, set_failed, set_mem in *; cbn in *.
  destruct (classical_dec (b IN s1.(mem_domain))) as [Hb|Hb]; cbn in Hf;
    [|exfalso; apply Hf; reflexivity].
  unfold UPDATE; destruct (decide (b = x)) as [<-|Hne].
  - exfalso; apply Hx; unfold s1 in Hb; rewrite write_mem_word_mem_domain in Hb; exact Hb.
  - apply IH; split; [exact Hf|exact Hx].
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "mem_op_outside_mem_domain" *)
Theorem mem_op_outside_mem_domain : forall m n (y : asm.addr a) s (x : word a),
  x NOTIN s.(mem_domain) /\ ~ (mem_op m n y s).(failed) ->
  (mem_op m n y s).(mem) x = s.(mem) x.
Proof.
  intros m n y s x [Hx Hf]; destruct m; cbn -[mem_load mem_store] in *;
    first
      [ unfold mem_load in *; cbv zeta in *;
        destruct (read_mem_word _ _ s) as [w s1] eqn:E; cbn -[read_mem_word];
        rewrite (read_mem_word_IMP_mem_eq _ _ _ _ _ E); reflexivity
      | unfold mem_store, assert, set_failed in *; cbv zeta in *;
        cbn -[write_mem_word] in *;
        apply write_mem_word_mem_eq; split; [|exact Hx];
        intro H; apply Hf; rewrite H, orb_true_r; reflexivity ].
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "inst_outside_mem_domain" *)
Theorem inst_outside_mem_domain : forall (i : asm.inst a) s (x : word a),
  x NOTIN s.(mem_domain) /\ ~ (inst i s).(failed) -> (inst i s).(mem) x = s.(mem) x.
Proof.
  intros i s x [Hx Hf]; destruct i as [| |y|m r y|y]; cbn -[arith_upd fp_upd mem_op] in *;
    try reflexivity.
  - rewrite (proj1 (proj2 (proj2 (arith_upd_consts y s)))); reflexivity.
  - apply mem_op_outside_mem_domain; split; assumption.
  - rewrite (proj1 (proj2 (proj2 (fp_upd_consts y s)))); reflexivity.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asm_outside_mem_domain" *)
Theorem asm_outside_mem_domain : forall (i : asm.asm a) p s (x : word a),
  x NOTIN s.(mem_domain) /\ ~ (asm i p s).(failed) -> (asm i p s).(mem) x = s.(mem) x.
Proof.
  intros i p s x [Hx Hf]; destruct i; cbn -[inst] in *; try reflexivity.
  - apply inst_outside_mem_domain; split; assumption.
  - destruct (word_cmp _ _ _); reflexivity.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "asm_step_outside_mem_domain" *)
Theorem asm_step_outside_mem_domain : forall (c : asm_config a) s1 i s2,
  asm_step c s1 i s2 ->
  forall (x : word a), x NOTIN s1.(mem_domain) -> s2.(mem) x = s1.(mem) x.
Proof.
  intros c s1 i s2 (_ & _ & _ & _ & <- & Hf & _) x Hx.
  apply asm_outside_mem_domain; split; assumption.
Qed.

(*! HOL "cakeml/compiler/encoders/asm/asmPropsScript.sml" "RTC_asm_step_outside_mem_domain" *)
Theorem RTC_asm_step_outside_mem_domain : forall (c : asm_config a) s1 s2,
  RTC (fun s1 s2 => exists i, asm_step c s1 i s2) s1 s2 ->
  forall ad, ad NOTIN s1.(mem_domain) -> s2.(mem) ad = s1.(mem) ad.
Proof.
  intros c s1 s2 H; induction H as [x|x y z (i & Hs) Hr IH]; intros ad Had; [reflexivity|].
  pose proof (asm_step_outside_mem_domain c x i y Hs ad Had) as E.
  destruct Hs as (_ & _ & _ & _ & <- & _).
  rewrite IH; [exact E|].
  rewrite (proj2 (proj2 (proj2 (asm_consts i _ x)))); exact Had.
Qed.

End Consts.
