(** * HOL4 [pegexec]: an executable PEG interpreter

    Port of [HOL/examples/formal-languages/context-free/pegexecScript.sml].

    HOL defines the interpreter as a continuation machine: [coreloop G]
    iterates a one-step function on [evalcase] states with [OWHILE] until a
    [Result] is reached ([NONE] if never), and [peg_exec]/[applykont] read
    the final state ([Looped] if the loop does not terminate).  These HOL
    definitions are ported as they are ([coreloop_def], [peg_exec_def],
    [applykont_def]); they are not executable ([OWHILE] decides termination
    classically).  The step function is [coreloop_step] (HOL's lambda,
    named).  [OWHILE] is HOL's [While$OWHILE_def]
    (with [num] = [N]); it is not yet in [While.v] and is defined here,
    untagged ([FUNPOW] is [arithmetic]'s).

    ** Execution (Galette)

    [coreloop_acc lk G hlk s H] runs the machine from [s] until it reaches a
    [Result] or [Looped] state, by structural recursion on a proof
    [H : Acc (Rstep G) s] that it does so.  The proof is erased by
    extraction, which leaves a plain tail-recursive loop over
    [coreloop_step_exec] (the step function with one rule lookup per
    nonterminal instead of two, through a lookup function [lk] proved equal
    to [FLOOKUP (rules G)]; [coreloop_step_exec_eq]).  Proved:

    - [coreloop_acc_run]: for every [H], [coreloop_acc lk G hlk s H] is HOL's
      result ([run G s], i.e. [peg_exec]/[applykont]).
    - [run_Result_Acc]: whenever HOL's result is a [Result r], the [Acc]
      proof exists.  With HOL's [peg_eval_total] and [exec_correct]
      ([peg_exec_Acc]): for a well-formed grammar ([wfG]) the machine
      started on any expression of [Gexprs G] (or any [nt n f] with
      [n IN FDOM G.rules]) with HOL's initial continuations terminates.

    So no fuel bound is involved: for a well-formed grammar the executable
    interpreter computes exactly HOL's [peg_exec] on every input.

    Not ported: [peg_exec_thm], [applykont_thm], [peg_nt_thm] (equation
    lists generated by ML code whose exact shapes are not reproduced; the
    same equations are the untagged [run_*] lemmas used below). *)

From Galette Require Import Base.
From Galette.HOL.src.num.theories Require Import arithmetic While.
From Galette.HOL.src.list.src Require Import list.
From Galette.HOL.src.coretypes Require Import option pair.
From Galette.HOL.src.pred_set.src Require Import pred_set.
From Galette.HOL.src.finite_maps Require Import finite_map.
From Galette.HOL.examples.formal_languages.context_free Require Import location grammar peg.
Open Scope N_scope.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "kont" *)
Inductive kont (A B C E : Type) : Type :=
| ksym : pegsym A B C E -> kont A B C E -> kont A B C E -> kont A B C E
| appf1 : (C -> C) -> kont A B C E -> kont A B C E
| appf2 : (C -> C -> C) -> kont A B C E -> kont A B C E
| dropErr : kont A B C E -> kont A B C E
| addErr : locs -> E -> kont A B C E -> kont A B C E
| cmpErrs : kont A B C E -> kont A B C E
| cmpEO : option (locs * E) -> kont A B C E -> kont A B C E
| returnTo : list (A * locs) -> list (option C) -> kont A B C E -> kont A B C E
| restoreEO : option (locs * E) -> kont A B C E -> kont A B C E
| poplist : (list C -> C) -> kont A B C E -> kont A B C E
| listsym : pegsym A B C E -> (list C -> C) -> kont A B C E -> kont A B C E
| done : kont A B C E
| failed : kont A B C E.
Arguments ksym {A B C E} _ _ _.
Arguments appf1 {A B C E} _ _.
Arguments appf2 {A B C E} _ _.
Arguments dropErr {A B C E} _.
Arguments addErr {A B C E} _ _ _.
Arguments cmpErrs {A B C E} _.
Arguments cmpEO {A B C E} _ _.
Arguments returnTo {A B C E} _ _ _.
Arguments restoreEO {A B C E} _ _.
Arguments poplist {A B C E} _ _.
Arguments listsym {A B C E} _ _ _.
Arguments done {A B C E}.
Arguments failed {A B C E}.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "poplist_aux_def" *)
Fixpoint poplist_aux {C} (acc : list C) (l : list (option C)) : list C * list (option C) :=
  match l with
  | SOME h :: t => poplist_aux (h :: acc) t
  | NONE :: t => (acc, t)
  | [] => (acc, [])
  end.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "poplistval_def" *)
Definition poplistval {C} (f : list C -> C) (l : list (option C)) : list (option C) :=
  let (values, rest) := poplist_aux [] l in SOME (f values) :: rest.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "evalcase" *)
Inductive evalcase (A B C E : Type) : Type :=
| EV : pegsym A B C E -> list (A * locs) -> list (option C) -> option (locs * E) ->
       list (locs * E) -> kont A B C E -> kont A B C E -> evalcase A B C E
| AP : kont A B C E -> list (A * locs) -> list (option C) -> option (locs * E) ->
       list (locs * E) -> evalcase A B C E
| Result : pegresult (list (A * locs)) C E -> evalcase A B C E
| Looped : evalcase A B C E.
Arguments EV {A B C E} _ _ _ _ _ _ _.
Arguments AP {A B C E} _ _ _ _ _.
Arguments Result {A B C E} _.
Arguments Looped {A B C E}.

(** ** HOL's [FUNPOW] and [OWHILE] *)

Definition OWHILE {S} (G : S -> bool) (f : S -> S) (s : S) : option S :=
  if classical_dec (exists n, ~ G (FUNPOW f n s))
  then SOME (FUNPOW f (LEAST (fun n => ~ G (FUNPOW f n s))) s)
  else NONE.

Lemma OWHILE_THM {S} (G : S -> bool) f s :
  OWHILE G f s = if G s then OWHILE G f (f s) else SOME s.
Proof.
  unfold OWHILE.
  destruct (G s) eqn:Gs.
  - assert (Hex : (exists n, ~ G (FUNPOW f n s)) <-> (exists n, ~ G (FUNPOW f n (f s)))).
    { split.
      - intros [n hn]; destruct (N.eq_dec n 0) as [->|hn0].
        + exfalso; apply hn; exact Gs.
        + exists (N.pred n); rewrite <- FUNPOW_SUC_r, N.succ_pred by exact hn0; exact hn.
      - intros [n hn]; exists (N.succ n); rewrite FUNPOW_SUC_r; exact hn. }
    destruct (classical_dec (exists n, ~ G (FUNPOW f n s))) as [h1|h1];
    destruct (classical_dec (exists n, ~ G (FUNPOW f n (f s)))) as [h2|h2];
      try tauto.
    f_equal.
    destruct h2 as [m hm].
    set (L := LEAST (fun n => ~ G (FUNPOW f n (f s)))).
    destruct (LEAST_spec (fun n => ~ G (FUNPOW f n (f s))) m hm) as [hL1 hL2]; fold L in hL1, hL2.
    rewrite (LEAST_unique (fun n => ~ G (FUNPOW f n s)) (N.succ L)).
    + apply FUNPOW_SUC_r.
    + rewrite FUNPOW_SUC_r; exact hL1.
    + intros k hk; destruct (N.eq_dec k 0) as [->|hk0].
      * cbn; rewrite Gs; auto.
      * rewrite <- (N.succ_pred k) by exact hk0; rewrite FUNPOW_SUC_r.
        apply hL2; lia.
  - destruct (classical_dec (exists n, ~ G (FUNPOW f n s))) as [h1|h1].
    + f_equal; rewrite (LEAST_unique _ 0); [reflexivity| |intros; lia].
      cbn; rewrite Gs; discriminate.
    + exfalso; apply h1; exists 0; cbn; rewrite Gs; discriminate.
Qed.

Lemma OWHILE_EQ_NONE {S} (G : S -> bool) f s :
  OWHILE G f s = NONE <-> forall n, G (FUNPOW f n s).
Proof.
  unfold OWHILE; destruct (classical_dec _) as [h|h]; split; try discriminate.
  - intros hall; exfalso; destruct h as [n hn]; apply hn, hall.
  - intros _ n; destruct (G (FUNPOW f n s)) eqn:E; [reflexivity|].
    exfalso; apply h; exists n; rewrite E; discriminate.
  - intros _; reflexivity.
Qed.

Lemma OWHILE_SOME_exists {S} (G : S -> bool) f s x :
  OWHILE G f s = SOME x -> exists n, ~ G (FUNPOW f n s) /\ x = FUNPOW f n s.
Proof.
  unfold OWHILE; destruct (classical_dec _) as [[m hm]|h]; [|discriminate].
  intros E; injection E as <-; eexists; split; [|reflexivity].
  apply (LEAST_spec (fun n => ~ G (FUNPOW f n s)) m hm).
Qed.

(** ** The machine *)

Section Machine.
Context {A B C E : Type}.

#[local] Abbreviation OME := (optmax MAXerr).
#[local] Abbreviation EOF := (Locs EOFpt EOFpt).

(** HOL's step function (the second argument of [OWHILE] in [coreloop_def]). *)
Definition coreloop_step (G : peg A B C E) (s : evalcase A B C E) : evalcase A B C E :=
  match s with
  | EV (empty v) i r eo errs k fk => AP k i (SOME v :: r) eo errs
  | EV (any tf) i r eo errs k fk =>
      match i with
      | [] => let err := (EOF, anyEOF G) in AP fk i r (OME eo (SOME err)) (err :: errs)
      | h :: t => AP k t (SOME (tf h) :: r) eo errs
      end
  | EV (tok P tf2) i r eo errs k fk =>
      match i with
      | [] => let err := (EOF, tokEOF G) in AP fk i r (OME eo (SOME err)) (err :: errs)
      | h :: t =>
          if P (FST h) then AP k t (SOME (tf2 h) :: r) eo errs
          else let err := (sloc i, tokFALSE G) in AP fk i r (OME eo (SOME err)) (err :: errs)
      end
  | EV (nt n tf3) i r eo errs k fk =>
      if decide (n IN FDOM (rules G))
      then EV (FAPPLY (rules G) n) i r eo errs (appf1 tf3 k) fk
      else Looped
  | EV (seq e1 e2 f) i r eo errs k fk =>
      EV e1 i r eo errs (restoreEO eo (ksym e2 (appf2 f k) (cmpEO eo (returnTo i r fk)))) fk
  | EV (choice e1 e2 cf) i r eo errs k fk =>
      EV e1 i r eo errs (appf1 (fun x => cf (inl x)) k)
         (returnTo i r (ksym e2 (dropErr (appf1 (fun x => cf (inr x)) k)) (cmpErrs fk)))
  | EV (rpt e lf) i r eo errs k fk =>
      EV e i (NONE :: r) eo errs (restoreEO eo (listsym e lf k)) (poplist lf k)
  | EV (not e v) i r eo errs k fk =>
      EV e i r eo errs (restoreEO eo (returnTo i r (addErr (sloc i) (notFAIL G) fk)))
         (restoreEO eo (returnTo i (SOME v :: r) (dropErr k)))
  | EV (error err) i r eo errs k fk =>
      let err := (sloc i, err) in AP fk i r (OME eo (SOME err)) (err :: errs)
  | AP done i [] _ _ => Looped
  | AP done i (NONE :: t) _ _ => Looped
  | AP done i (SOME rv :: _) eo _ => Result (Success i rv eo)
  | AP failed i r _ [] => Looped
  | AP failed i r _ ((l, e) :: _) => Result (Failure l e)
  | AP (dropErr _) i r _ [] => Looped
  | AP (dropErr k) i r eo (_ :: t) => AP k i r eo t
  | AP (addErr l e k) i r eo errs => AP k i r (OME eo (SOME (l, e))) ((l, e) :: errs)
  | AP (cmpErrs k) i r _ [] => Looped
  | AP (cmpErrs k) i r _ [_] => Looped
  | AP (cmpErrs k) i r eo ((l2, er2) :: (l1, er1) :: rest) =>
      AP k i r eo ((if locsle l1 l2 then (l2, er2) else (l1, er1)) :: rest)
  | AP (cmpEO eo1 k) i r eo2 [] => Looped
  | AP (cmpEO eo1 k) i r eo2 ((l, err) :: rest) =>
      AP k i r (OME eo1 (SOME (l, err))) ((l, err) :: rest)
  | AP (ksym e k fk) i r eo errs => EV e i r eo errs k fk
  | AP (appf1 f1 k) i (SOME v :: r) eo errs => AP k i (SOME (f1 v) :: r) eo errs
  | AP (appf1 _ _) _ _ _ _ => Looped
  | AP (appf2 f2 k) i (SOME v1 :: SOME v2 :: r) eo errs => AP k i (SOME (f2 v2 v1) :: r) eo errs
  | AP (appf2 _ _) _ _ _ _ => Looped
  | AP (returnTo i r k) i' r' eo errs => AP k i r eo errs
  | AP (restoreEO eo k) i r eo' errs => AP k i r eo errs
  | AP (listsym e f k) i r eo errs =>
      EV e i r eo errs (restoreEO eo (listsym e f k)) (poplist f k)
  | AP (poplist f k) i r eo [] => Looped
  | AP (poplist f k) i r eo (e :: errs) => AP k i (poplistval f r) eo errs
  | Result r => Result r
  | Looped => Looped
  end.

Definition notResult (s : evalcase A B C E) : bool :=
  match s with Result _ => false | _ => true end.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "coreloop_def" *)
Definition coreloop (G : peg A B C E) : evalcase A B C E -> option (evalcase A B C E) :=
  OWHILE notResult (coreloop_step G).

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "peg_exec_def" *)
Definition peg_exec (G : peg A B C E) e i r eo errs k fk : evalcase A B C E :=
  match coreloop G (EV e i r eo errs k fk) with SOME r => r | NONE => Looped end.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "applykont_def" *)
Definition applykont (G : peg A B C E) k i r eo errs : evalcase A B C E :=
  match coreloop G (AP k i r eo errs) with SOME r => r | NONE => Looped end.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "coreloop_result" *)
Theorem coreloop_result : forall G x, coreloop G (Result x) = SOME (Result x).
Proof. intros; unfold coreloop; rewrite OWHILE_THM; reflexivity. Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "coreloop_Looped" *)
Theorem coreloop_Looped : forall G, coreloop G Looped = NONE.
Proof.
  intros G; unfold coreloop; apply OWHILE_EQ_NONE; intros n.
  induction n as [|n IH] using N.peano_ind; [reflexivity|].
  rewrite FUNPOW_SUC_r; exact IH.
Qed.

(** [run G s]: HOL's result of running the machine from [s]. *)
Definition run (G : peg A B C E) (s : evalcase A B C E) : evalcase A B C E :=
  match coreloop G s with SOME r => r | NONE => Looped end.

Lemma run_step G s : notResult s = true -> run G s = run G (coreloop_step G s).
Proof. intros h; unfold run, coreloop; rewrite (OWHILE_THM _ _ s), h; reflexivity. Qed.

Lemma run_Result G r : run G (Result r) = Result r.
Proof. unfold run; rewrite coreloop_result; reflexivity. Qed.

Lemma run_Looped G : run G Looped = Looped.
Proof. unfold run; rewrite coreloop_Looped; reflexivity. Qed.

Lemma peg_exec_run G e i r eo errs k fk :
  peg_exec G e i r eo errs k fk = run G (EV e i r eo errs k fk).
Proof. reflexivity. Qed.

Lemma applykont_run G k i r eo errs : applykont G k i r eo errs = run G (AP k i r eo errs).
Proof. reflexivity. Qed.

Lemma run_EV G e i r eo errs k fk :
  run G (EV e i r eo errs k fk) = run G (coreloop_step G (EV e i r eo errs k fk)).
Proof. apply run_step; reflexivity. Qed.

Lemma run_AP G k i r eo errs :
  run G (AP k i r eo errs) = run G (coreloop_step G (AP k i r eo errs)).
Proof. apply run_step; reflexivity. Qed.

(** ** Correctness *)

Lemma OME_NONE (eo : option (locs * E)) : OME NONE eo = eo /\ OME eo NONE = eo.
Proof. destruct eo; split; reflexivity. Qed.

Lemma OME_ASSOC (eo1 eo2 eo3 : option (locs * E)) :
  OME eo1 (OME eo2 eo3) = OME (OME eo1 eo2) eo3.
Proof.
  destruct eo1 as [[l1 e1]|], eo2 as [[l2 e2]|], eo3 as [[l3 e3]|]; cbn; try reflexivity.
  f_equal; unfold MAXerr.
  destruct (locsle l2 l3) eqn:h23, (locsle l1 l2) eqn:h12; cbn;
    try rewrite h23; try rewrite h12; try reflexivity.
  - rewrite (locsle_TRANS l1 l2 l3 (conj h12 h23)); reflexivity.
  - destruct (locsle l1 l3) eqn:h13; [|reflexivity].
    destruct (locsle_total l2 l3) as [h|h]; [congruence|].
    destruct (locsle_total l1 l2) as [h'|h']; [congruence|].
    (* l3 <= l2 <= l1 <= l3 *)
    pose proof (locsle_TRANS l3 l2 l1 (conj h h')) as h31.
    destruct l1 as [a1 b1], l2 as [a2 b2], l3 as [a3 b3]; cbn in *.
    assert (a1 = a3) as -> by (apply locnle_ANTISYM; split; assumption).
    assert (a2 = a3) as -> by (apply locnle_ANTISYM; split; assumption).
    rewrite locnle_REFL in h23; discriminate.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "MAXerr_id" *)
Theorem MAXerr_id : forall x : locs * E, MAXerr x x = x.
Proof. intros [l e]; unfold MAXerr; rewrite locsle_REFL; reflexivity. Qed.

Ltac is_concrete_sym e :=
  lazymatch e with
  | empty _ => idtac | any _ => idtac | tok _ _ => idtac | nt _ _ => idtac
  | seq _ _ _ => idtac | choice _ _ _ => idtac | rpt _ _ => idtac | not _ _ => idtac
  | error _ => idtac
  end.

Ltac is_concrete_k k :=
  lazymatch k with
  | ksym _ _ _ => idtac | appf1 _ _ => idtac | appf2 _ _ => idtac | dropErr _ => idtac
  | addErr _ _ _ => idtac | cmpErrs _ => idtac | cmpEO _ _ => idtac
  | returnTo _ _ _ => idtac | restoreEO _ _ => idtac | poplist _ _ => idtac
  | listsym _ _ _ => idtac | done => idtac | failed => idtac
  end.

(** One machine step on the left-hand side, when its head is known. *)
Ltac lhs_step :=
  lazymatch goal with
  | |- run ?G (EV ?e ?i ?r ?eo ?errs ?k ?fk) = _ =>
      is_concrete_sym e; rewrite (run_EV G e i r eo errs k fk); cbn [coreloop_step]
  | |- run ?G (AP ?k ?i ?r ?eo ?errs) = _ =>
      is_concrete_k k; rewrite (run_AP G k i r eo errs); cbn [coreloop_step]
  end.

(** Rewrite the left-hand side with an induction hypothesis. *)
Ltac lhs_ih :=
  lazymatch goal with
  | |- run ?G (EV ?e ?i _ _ _ _ _) = _ =>
      match goal with
      | H : context [run G (EV e i _ _ _ _ _)] |- _ => erewrite H by reflexivity
      end
  end.

Ltac run_go := repeat (first [lhs_ih | lhs_step]).

Lemma poplist_aux_MAP (vs : list C) stk acc :
  poplist_aux acc (MAP SOME vs ++ NONE :: stk) = (REVERSE vs ++ acc, stk).
Proof.
  revert acc; induction vs as [|v vs IH]; intros acc; [reflexivity|].
  cbn [List.map app poplist_aux]; rewrite IH; cbn; rewrite <- app_assoc; reflexivity.
Qed.

Lemma exec_correct_run (G : peg A B C E) :
  (forall p res, peg_eval G p res ->
     (forall j v eo eo0 k fk stk errs,
        res = Success j v eo ->
        run G (EV (snd p) (fst p) stk eo0 errs k fk) =
        run G (AP k j (SOME v :: stk) (OME eo0 eo) errs)) /\
     (forall k fk stk eo errs l err,
        res = Failure l err ->
        run G (EV (snd p) (fst p) stk eo errs k fk) =
        run G (AP fk (fst p) stk (OME eo (SOME (l, err))) ((l, err) :: errs)))) /\
  (forall p q, peg_eval_list G p q ->
     forall f k stk eo errs vs,
       run G (EV (snd p) (fst p) (MAP SOME vs ++ (NONE :: stk)) eo errs
         (restoreEO eo (listsym (snd p) f k)) (poplist f k)) =
       run G (AP k (fst q) (SOME (f (REVERSE vs ++ fst (snd q))) :: stk)
         (OME eo (SOME (snd (snd q)))) errs)).
Proof.
  apply peg_eval_mutind; cbn [fst snd]; intros;
    repeat match goal with H : _ /\ _ |- _ => destruct H end;
    repeat split; intros; try discriminate;
    repeat match goal with
    | H : Success _ _ _ = Success _ _ _ |- _ => injection H; clear H; intros; subst
    | H : Failure _ _ = Failure _ _ |- _ => injection H; clear H; intros; subst
    | H : resultmap _ ?r = Success _ _ _ |- _ =>
        apply resultmap_EQ_Success in H; destruct H as [? [? ?]]; subst
    | H : resultmap _ ?r = Failure _ _ |- _ => apply resultmap_EQ_Failure in H; subst
    | H : UNCURRY Failure ?x = Success _ _ _ |- _ => destruct x; discriminate
    | H : UNCURRY Failure (MAXerr ?a ?b) = Failure _ _ |- _ =>
        rewrite UNCURRY_Failure_isFailure in H; injection H; clear H; intros; subst
    | H : is_true (isFailure ?r) |- _ => destruct r; [discriminate H|clear H]
    | H : is_true (isSuccess ?r) |- _ => destruct r; [clear H|discriminate H]
    end.
  (* nt *)
  all: try (lazymatch goal with |- run _ (EV (nt ?n _) _ _ _ _ _ _) = _ =>
              rewrite run_EV; cbn [coreloop_step];
              destruct (decide (n IN FDOM (rules G))); [|contradiction] end).
  all: run_go.
  all: try match goal with
       | H : is_true (?P ?x) |- context [if ?P ?x then _ else _] => rewrite H
       | H : ~ is_true (?P ?x) |- context [if ?P ?x then _ else _] =>
           let E := fresh in destruct (P x) eqn:E; [contradiction|]
       end.
  all: cbn [sloc]; rewrite ?(proj2 (OME_NONE _)), ?(proj1 (OME_NONE _)); try reflexivity.
  all: try (match goal with |- run _ (if ?b then _ else _) = _ =>
              destruct b eqn:?; [exfalso; unfold is_true in *; tauto|reflexivity] end).
  (* choice_fail *)
  - rewrite <- OME_ASSOC; unfold MAXerr; cbn [optmax MAXerr];
      destruct (locsle fl1 fl2); reflexivity.
  (* choice_success2 *)
  - rewrite <- OME_ASSOC; reflexivity.
  (* rpt *)
  - match goal with H : forall f k stk eo errs vs, _ |- _ =>
      specialize (H f k stk eo0 errs []); cbn in H; rewrite H end; reflexivity.
  (* list_nil *)
  - unfold poplistval; rewrite poplist_aux_MAP, app_nil_r; reflexivity.
  (* list_cons *)
  - match goal with H : forall f k stk eo errs vs, _ |- _ =>
      specialize (H f k stk eo1 errs (c :: vs)); cbn [List.map app] in H; rewrite H end.
    cbn [List.rev]; rewrite <- app_assoc; reflexivity.
Qed.


(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "exec_correct" *)
Theorem exec_correct : forall G : peg A B C E,
  (forall i e j v eo eo0 k fk stk errs,
     peg_eval G (i, e) (Success j v eo) ->
     peg_exec G e i stk eo0 errs k fk = applykont G k j (SOME v :: stk) (OME eo0 eo) errs) /\
  (forall i e k fk stk eo errs l err,
     peg_eval G (i, e) (Failure l err) ->
     peg_exec G e i stk eo errs k fk =
     applykont G fk i stk (OME eo (SOME (l, err))) ((l, err) :: errs)) /\
  (forall i e j vlist err f k stk eo errs vs,
     peg_eval_list G (i, e) (j, (vlist, err)) ->
     peg_exec G e i (MAP SOME vs ++ (NONE :: stk)) eo errs (restoreEO eo (listsym e f k))
       (poplist f k) =
     applykont G k j (SOME (f (REVERSE vs ++ vlist)) :: stk) (OME eo (SOME err)) errs).
Proof.
  intros G; destruct (exec_correct_run G) as [h1 h2]; repeat split; intros.
  - exact (proj1 (h1 _ _ H) _ _ _ _ _ _ _ _ eq_refl).
  - exact (proj2 (h1 _ _ H) _ _ _ _ _ _ _ eq_refl).
  - exact (h2 _ _ H f k stk eo errs vs).
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "pegexec_succeeds" *)
Theorem pegexec_succeeds : forall (G : peg A B C E) i e j v eo eo0,
  peg_eval G (i, e) (Success j v eo) ->
  peg_exec G e i [] eo0 [] done failed = Result (Success j v (OME eo0 eo)).
Proof.
  intros; rewrite (proj1 (exec_correct G) _ _ _ _ _ _ done failed [] [] H).
  rewrite applykont_run, run_AP; cbn [coreloop_step]; apply run_Result.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "pegexec_fails" *)
Theorem pegexec_fails : forall (G : peg A B C E) i e l err eo,
  peg_eval G (i, e) (Failure l err) ->
  peg_exec G e i [] eo [] done failed = Result (Failure l err).
Proof.
  intros; rewrite (proj1 (proj2 (exec_correct G)) _ _ done failed [] eo [] _ _ H).
  rewrite applykont_run, run_AP; cbn [coreloop_step]; apply run_Result.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "pegexec" *)
Theorem pegexec : forall (G : peg A B C E) s e r,
  peg_eval G (s, e) r -> peg_exec G e s [] NONE [] done failed = Result r.
Proof.
  intros G s e [j v eo|l err] h.
  - rewrite (pegexec_succeeds _ _ _ _ _ _ NONE h); destruct eo; reflexivity.
  - apply pegexec_fails, h.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "peg_eval_executed" *)
Theorem peg_eval_executed : forall (G : peg A B C E) s e r,
  wfG G /\ e IN Gexprs G ->
  (peg_eval G (s, e) r <-> peg_exec G e s [] NONE [] done failed = Result r).
Proof.
  intros G s e r [hwf he]; split; [apply pegexec|].
  intros h; destruct (peg_eval_total G hwf s e he) as [r' hr'].
  rewrite (pegexec _ _ _ _ hr') in h; injection h as ->; exact hr'.
Qed.

#[local] Instance pegresult_inhabited {X} `{Inhabited C} : Inhabited (pegresult (list X) C E) :=
  Success [] (inhabitant C) NONE.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "destResult_def" *)
Definition destResult `{Inhabited C} (r : evalcase A B C E) : pegresult (list (A * locs)) C E :=
  match r with Result r => r | _ => ARB end.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "pegparse_def" *)
Definition pegparse `{Inhabited C} (G : peg A B C E) (s : list (A * locs))
    : option (list (A * locs) * (C * option (locs * E))) :=
  if classical_dec (wfG G) then
    match destResult (peg_exec G (start G) s [] NONE [] done failed) with
    | Success s v eo => SOME (s, (v, eo))
    | _ => NONE
    end
  else NONE.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "pegparse_eq_SOME" *)
Theorem pegparse_eq_SOME `{Inhabited C} : forall (G : peg A B C E) s s' v eo,
  pegparse G s = SOME (s', (v, eo)) <-> wfG G /\ peg_eval G (s, start G) (Success s' v eo).
Proof.
  intros G s s' v eo; unfold pegparse.
  destruct (classical_dec (wfG G)) as [hwf|hwf]; [|split; [discriminate|tauto]].
  destruct (peg_eval_total G hwf s (start G) (start_IN_Gexprs G)) as [r hr].
  rewrite (pegexec _ _ _ _ hr); cbn [destResult].
  split.
  - destruct r as [j w e0|]; [|discriminate]; intros h; injection h as -> -> ->; auto.
  - intros [_ h]; apply (proj1 (proj1 (peg_deterministic G) _ _ _ hr _)) in h; subst r;
      reflexivity.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "pegparse_eq_NONE" *)
Theorem pegparse_eq_NONE `{Inhabited C} : forall (G : peg A B C E) s,
  pegparse G s = NONE <-> ~ wfG G \/ exists l e, peg_eval G (s, start G) (Failure l e).
Proof.
  intros G s; unfold pegparse.
  destruct (classical_dec (wfG G)) as [hwf|hwf]; [|split; [intros; left; exact hwf|reflexivity]].
  destruct (peg_eval_total G hwf s (start G) (start_IN_Gexprs G)) as [r hr].
  rewrite (pegexec _ _ _ _ hr); cbn [destResult].
  split.
  - destruct r as [j w e0|l e]; [discriminate|]; intros _; right; eauto.
  - intros [h|[l [e h]]]; [contradiction|].
    apply (proj1 (proj1 (peg_deterministic G) _ _ _ hr _)) in h; subst r; reflexivity.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "peg_exec_total" *)
Theorem peg_exec_total : forall (G : peg A B C E) i,
  wfG G -> exists r, peg_exec G (start G) i [] NONE [] done failed = Result r.
Proof.
  intros G i hwf; destruct (peg_eval_total G hwf i (start G) (start_IN_Gexprs G)) as [r hr].
  exists r; apply pegexec, hr.
Qed.

(*! HOL "HOL/examples/formal-languages/context-free/pegexecScript.sml" "coreloop_total" *)
Theorem coreloop_total : forall (G : peg A B C E) i,
  wfG G -> exists r, coreloop G (EV (start G) i [] NONE [] done failed) = SOME (Result r).
Proof.
  intros G i hwf; destruct (peg_exec_total G i hwf) as [r hr]; exists r.
  unfold peg_exec in hr; destruct (coreloop G _) eqn:Ec; [congruence|discriminate].
Qed.

(** ** Executable interpreter (Galette)

    See the header.  [coreloop_step_exec] is [coreloop_step] with a single
    [FLOOKUP] for a nonterminal. *)

Definition coreloop_step_exec (lk : inf B -> option (pegsym A B C E)) (G : peg A B C E)
    (s : evalcase A B C E) : evalcase A B C E :=
  match s with
  | EV (nt n tf3) i r eo errs k fk =>
      match lk n with
      | Some e => EV e i r eo errs (appf1 tf3 k) fk
      | None => Looped
      end
  | _ => coreloop_step G s
  end.

Lemma coreloop_step_exec_eq lk G s :
  (forall n, lk n = FLOOKUP (rules G) n) -> coreloop_step_exec lk G s = coreloop_step G s.
Proof.
  intros hlk; destruct s as [e i r eo errs k fk| | |]; try reflexivity.
  destruct e; try reflexivity.
  cbv beta iota delta [coreloop_step_exec coreloop_step]; rewrite hlk.
  destruct (decide (i0 IN FDOM (rules G))) as [h|h]; unfold FDOM in h; unfold_sets;
    unfold FAPPLY, THE; destruct (FLOOKUP (rules G) i0) eqn:Ef; try reflexivity;
    exfalso; apply h; [reflexivity|discriminate].
Qed.

Definition halted (s : evalcase A B C E) : bool :=
  match s with Result _ | Looped => true | _ => false end.

(** [Rstep G s' s]: [s'] is the successor of the running state [s]. *)
Definition Rstep (G : peg A B C E) (s' s : evalcase A B C E) : Prop :=
  halted s = false /\ s' = coreloop_step G s.

(** [lk] is the finite-map lookup [FLOOKUP (rules G)], or any function
    provably equal to it ([hlk]); a client may pass a faster one. *)
Fixpoint coreloop_acc (lk : inf B -> option (pegsym A B C E)) (G : peg A B C E)
    (hlk : forall n, lk n = FLOOKUP (rules G) n)
    (s : evalcase A B C E) (H : Acc (Rstep G) s) {struct H} : evalcase A B C E :=
  match H with
  | Acc_intro _ f =>
      match s as s0 return (forall y, Rstep G y s0 -> Acc (Rstep G) y) -> evalcase A B C E with
      | Result r => fun _ => Result r
      | Looped => fun _ => Looped
      | s0 => fun f0 =>
          coreloop_acc lk G hlk (coreloop_step_exec lk G s0)
            (f0 _ (conj eq_refl (coreloop_step_exec_eq lk G s0 hlk)))
      end f
  end.

Lemma coreloop_acc_run lk G hlk s (H : Acc (Rstep G) s) : coreloop_acc lk G hlk s H = run G s.
Proof.
  assert (Hs := H); revert H; induction Hs as [s _ IH]; intros [f].
  destruct s as [e i r eo errs k fk|k i r eo errs|r|]; cbn [coreloop_acc].
  - rewrite IH by (split; [reflexivity|apply coreloop_step_exec_eq, hlk]).
    rewrite (coreloop_step_exec_eq lk G _ hlk), <- run_EV; reflexivity.
  - rewrite IH by (split; [reflexivity|apply coreloop_step_exec_eq, hlk]).
    rewrite (coreloop_step_exec_eq lk G _ hlk), <- run_AP; reflexivity.
  - symmetry; apply run_Result.
  - symmetry; apply run_Looped.
Qed.

Lemma halts_Acc G n s :
  notResult (FUNPOW (coreloop_step G) n s) = false -> Acc (Rstep G) s.
Proof.
  revert s; induction n as [|n IH] using N.peano_ind; intros s h.
  - constructor; intros y [hh _]; destruct s; discriminate.
  - constructor; intros y [hh ->]; apply IH.
    rewrite <- FUNPOW_SUC_r; exact h.
Qed.

Lemma run_Result_Acc G s r : run G s = Result r -> Acc (Rstep G) s.
Proof.
  unfold run; destruct (coreloop G s) as [x|] eqn:Ec; [|discriminate].
  intros ->; apply OWHILE_SOME_exists in Ec; destruct Ec as [n [hn _]].
  apply (halts_Acc G n); destruct (notResult _); [exfalso; apply hn; reflexivity|reflexivity].
Qed.

(** For a well-formed grammar the machine terminates from HOL's initial
    continuations, on every expression of the grammar ... *)
Theorem peg_exec_Acc (G : peg A B C E) e s :
  wfG G -> e IN Gexprs G -> Acc (Rstep G) (EV e s [] NONE [] done failed).
Proof.
  intros hwf he; destruct (peg_eval_total G hwf s e he) as [r hr].
  apply (run_Result_Acc _ _ r), (pegexec _ _ _ _ hr).
Qed.

(** ... and on every nonterminal of its domain. *)
Theorem peg_exec_nt_Acc (G : peg A B C E) n f s :
  wfG G -> n IN FDOM (rules G) -> Acc (Rstep G) (EV (nt n f) s [] NONE [] done failed).
Proof.
  intros hwf hn.
  assert (he : FAPPLY (rules G) n IN Gexprs G).
  { unfold Gexprs; unfold_sets.
    exists (subexprs (FAPPLY (rules G) n)); split; [|apply subexprs_included].
    exists (FAPPLY (rules G) n); split; [reflexivity|right].
    apply IN_FRANGE; eauto. }
  destruct (peg_eval_total G hwf s _ he) as [r hr].
  apply (run_Result_Acc _ _ (resultmap f r)), pegexec, peg_eval_nt; assumption.
Qed.

(** The executable interpreter computes HOL's [peg_exec]. *)
Theorem coreloop_acc_peg_exec lk G hlk e s (H : Acc (Rstep G) (EV e s [] NONE [] done failed)) :
  coreloop_acc lk G hlk _ H = peg_exec G e s [] NONE [] done failed.
Proof. apply coreloop_acc_run. Qed.

End Machine.
